import { PlanetConfig } from '../types';

export const PLANETS: PlanetConfig[] = [
  // =========================================================================
  // 1. SMALL PLANETS (Compact Caverns, Agile Navigation, Tight Vaults)
  // =========================================================================
  {
    id: 'luna',
    name: 'Luna Core',
    category: 'Airless Moon • Tutorial World',
    sizeCategory: 'Small',
    width: 8600,
    height: 3200,
    description: 'Official Tutorial World. 3-tier subterranean lunar training caverns with complete vacuum. Learn thruster mechanics, inertia control, and cargo retrieval in this introductory flight sector.',
    gravity: 1.62,
    airResistance: 0.0000,
    fuelBurnRate: 4.5,
    surfacePressureBar: 0.00,
    surfaceTempC: -130,
    radiationRadPerHr: 0.85,
    windSpeedKmh: 0,
    hazards: ['Zero Atmosphere / No Aerodynamic Braking', 'Sharp Basalt Ceiling Spikes', 'Depot Trench Incline'],
    objectives: ['Launch from Sub-Level 1 Outpost', 'Extract Scientific Sensor Pod (Level 3)', 'Deliver Cargo to Level 2 Nexus Platform', 'Land on Primary Recovery Pad'],
    recommendedCraft: 'Apollo Recon / Wasp Scout',
    theme: {
      skyTop: '#05070c',
      skyBottom: '#0d131f',
      terrainFill: '#141824',
      terrainBorder: '#94a3b8',
      terrainAccent: '#38bdf8',
      gridColor: 'rgba(148, 163, 184, 0.06)',
      dustColor: '#cbd5e1',
      starDensity: 160,
      glowColor: 'rgba(56, 189, 248, 0.25)',
    },
    seed: 42001,
    targetTimeSec: 300,
    difficulty: 'Easy',
  },
  {
    id: 'phobos',
    name: 'Phobos Monolith',
    category: 'Microgravity Moonlet',
    sizeCategory: 'Small',
    width: 8600,
    height: 3200,
    description: 'Ultra-low mass Martian moon with jagged monolith pillars. Inertia control and gentle RCS micro-pulses are essential to avoid drifting into the cavern roof.',
    gravity: 0.65,
    airResistance: 0.0000,
    fuelBurnRate: 3.8,
    surfacePressureBar: 0.00,
    surfaceTempC: -112,
    radiationRadPerHr: 1.2,
    windSpeedKmh: 0,
    hazards: ['Extreme Drift Inertia', 'Monolith Rock Needles', 'Tight Vertical Exit Shafts'],
    objectives: ['Navigate Narrow Monolith Archway', 'Secure Mineral Isotope Pod', 'Touchdown Safely at Phobos Survey LZ'],
    recommendedCraft: 'Viper Dart / Kestrel Stunt Dart',
    theme: {
      skyTop: '#080511',
      skyBottom: '#150d26',
      terrainFill: '#130a21',
      terrainBorder: '#a855f7',
      terrainAccent: '#c084fc',
      gridColor: 'rgba(168, 85, 247, 0.06)',
      dustColor: '#e9d5ff',
      starDensity: 180,
      glowColor: 'rgba(168, 85, 247, 0.3)',
    },
    seed: 15403,
    targetTimeSec: 125,
    difficulty: 'Easy',
  },
  {
    id: 'europa',
    name: 'Europa Crevasse',
    sizeCategory: 'Small',
    category: 'Sub-Zero Ice Moonlet',
    width: 8600,
    height: 3200,
    description: 'Sub-surface cryogenic ice fissure with jagged hanging icicle bridges and narrow thermal vents. Watch for slippery touch-and-go landing perches.',
    gravity: 1.32,
    airResistance: 0.0002,
    fuelBurnRate: 4.4,
    surfacePressureBar: 0.05,
    surfaceTempC: -180,
    radiationRadPerHr: 22.4,
    windSpeedKmh: 12,
    hazards: ['Hanging Cryo-Icicle Spires', 'Sub-Zero Thermal Stress', 'Narrow Glacial S-Turn Tunnels'],
    objectives: ['Descent through Upper Ice Fissure', 'Retrieve Cryo Core from Shelf 2', 'Land on Sub-Glacial Research Hub'],
    recommendedCraft: 'Spectre Recon / Aegis Crawler',
    theme: {
      skyTop: '#021019',
      skyBottom: '#062030',
      terrainFill: '#081d2a',
      terrainBorder: '#38bdf8',
      terrainAccent: '#7dd3fc',
      gridColor: 'rgba(56, 189, 248, 0.07)',
      dustColor: '#bae6fd',
      starDensity: 150,
      glowColor: 'rgba(56, 189, 248, 0.3)',
    },
    seed: 71204,
    targetTimeSec: 150,
    difficulty: 'Medium',
  },
  {
    id: 'vesta',
    name: 'Vesta Iron Ridge',
    sizeCategory: 'Small',
    category: 'Metallic Asteroid Basin',
    width: 8600,
    height: 3200,
    description: 'Dense nickel-iron asteroid crater filled with magnetic ore towers and jagged slag overhangs. Heavy metallic obstacles require surgical vectoring.',
    gravity: 0.95,
    airResistance: 0.0000,
    fuelBurnRate: 4.0,
    surfacePressureBar: 0.00,
    surfaceTempC: -95,
    radiationRadPerHr: 1.8,
    windSpeedKmh: 0,
    hazards: ['Metallic Slag Outcroppings', 'Dense Vertical Rock Gates', 'High-Speed Rebound Hazards'],
    objectives: ['Weave through Asteroid Choke-points', 'Collect Fuel Reserve Cells', 'Execute Soft Landing on Outpost 4'],
    recommendedCraft: 'Viper Dart / Apollo Recon',
    theme: {
      skyTop: '#0c0a06',
      skyBottom: '#1c160e',
      terrainFill: '#1a130a',
      terrainBorder: '#f59e0b',
      terrainAccent: '#fbbf24',
      gridColor: 'rgba(245, 158, 11, 0.06)',
      dustColor: '#fde68a',
      starDensity: 170,
      glowColor: 'rgba(245, 158, 11, 0.28)',
    },
    seed: 39481,
    targetTimeSec: 190,
    difficulty: 'Medium',
  },

  // =========================================================================
  // 2. MEDIUM PLANETS (Extended Chambers, Moderate Drag, Multi-Tier Caves)
  // =========================================================================
  {
    id: 'ares',
    name: 'Ares Canyon',
    sizeCategory: 'Medium',
    category: 'Desert Planet',
    width: 8600,
    height: 3200,
    description: 'Multi-level jagged red sandstone caves with thin dust atmosphere. Transport the heavy Drill Core Matrix across geothermal shafts.',
    gravity: 3.72,
    airResistance: 0.0008,
    fuelBurnRate: 5.5,
    surfacePressureBar: 0.12,
    surfaceTempC: -45,
    radiationRadPerHr: 4.5,
    windSpeedKmh: 35,
    hazards: ['Atmospheric Dust Turbulence', 'Deep Geothermal Trench Basin', 'Hanging Sandstone Caldera Overhangs'],
    objectives: ['Launch from High Mesa Platform', 'Extract 350kg Drill Core Matrix', 'Deliver Drill to Lower Caldera LZ'],
    recommendedCraft: 'Aegis Crawler / Orion Surveyor',
    theme: {
      skyTop: '#130806',
      skyBottom: '#29100a',
      terrainFill: '#240d08',
      terrainBorder: '#f87171',
      terrainAccent: '#fb923c',
      gridColor: 'rgba(251, 146, 60, 0.07)',
      dustColor: '#fdba74',
      starDensity: 110,
      glowColor: 'rgba(248, 113, 113, 0.3)',
    },
    seed: 88412,
    targetTimeSec: 210,
    difficulty: 'Medium',
  },
  {
    id: 'titan',
    name: 'Titan Grotto',
    sizeCategory: 'Medium',
    category: 'Methane Cavern Moon',
    width: 8600,
    height: 3200,
    description: 'Low gravity with dense atmospheric drag. Navigate through deep methane fissure chambers to hoist the Cryo Fuel Cell.',
    gravity: 1.38,
    airResistance: 0.0032,
    fuelBurnRate: 4.8,
    surfacePressureBar: 1.45,
    surfaceTempC: -179,
    radiationRadPerHr: 0.3,
    windSpeedKmh: 48,
    hazards: ['Heavy Atmospheric Methane Drag', 'Fluid Vapor Updrafts', 'Subterranean Nitrogen Spires'],
    objectives: ['Ascend against Atmospheric Resistance', 'Extract High-Density Cryo Fuel Cell', 'Cross Chasm to Titan Grotto Hub'],
    recommendedCraft: 'Nebula Starchaser / Vanguard Exoship',
    theme: {
      skyTop: '#03141a',
      skyBottom: '#07242c',
      terrainFill: '#061a21',
      terrainBorder: '#2dd4bf',
      terrainAccent: '#34d399',
      gridColor: 'rgba(45, 212, 191, 0.08)',
      dustColor: '#99f6e4',
      starDensity: 70,
      glowColor: 'rgba(45, 212, 191, 0.35)',
    },
    seed: 51203,
    targetTimeSec: 245,
    difficulty: 'Medium',
  },
  {
    id: 'ceres',
    name: 'Ceres Hollow',
    sizeCategory: 'Medium',
    category: 'Subterranean Asteroid Labyrinth',
    description: 'Subterranean microgravity asteroid labyrinth. Inertia is your biggest challenge while maneuvering tethered isotope canisters through narrow rock shafts.',
    gravity: 0.78,
    airResistance: 0.0000,
    fuelBurnRate: 4.0,
    surfacePressureBar: 0.00,
    surfaceTempC: -105,
    radiationRadPerHr: 1.6,
    windSpeedKmh: 0,
    hazards: ['Zero-G Recoil Disorientation', 'Compound Pendulum Slinging', 'Narrow Cavern Ceiling Ribs'],
    objectives: ['Hook Isotope Canister in Deep Shaft', 'Pilot Tethered Load through 3 S-Bends', 'Deposit Isotope & Land at Ceres Vault'],
    recommendedCraft: 'Vanguard Exoship / Apollo Recon',
    theme: {
      skyTop: '#0a0518',
      skyBottom: '#170c32',
      terrainFill: '#160d2e',
      terrainBorder: '#c084fc',
      terrainAccent: '#e879f9',
      gridColor: 'rgba(192, 132, 252, 0.06)',
      dustColor: '#e9d5ff',
      starDensity: 190,
      glowColor: 'rgba(192, 132, 252, 0.3)',
    },
    seed: 19302,
    targetTimeSec: 230,
    difficulty: 'Medium',
  },
  {
    id: 'glacies',
    name: 'Glacies Chasm',
    sizeCategory: 'Medium',
    category: 'Sub-Zero Ice World',
    description: 'Subterranean glacial crevasses and icicle gates. Ferry cryogenic superconductors through ice arches and vertical draft chimneys.',
    gravity: 2.10,
    airResistance: 0.0003,
    fuelBurnRate: 4.8,
    surfacePressureBar: 0.15,
    surfaceTempC: -210,
    radiationRadPerHr: 0.4,
    windSpeedKmh: 28,
    hazards: ['Thermal Expansion Downdrafts', 'Cryo-Superconductor Fragility', 'Hanging Ice Archway Corridors'],
    objectives: ['Traverse Lower Glacial Crevasse', 'Extract Superconductor Container', 'Ascend Chimney to Surface Outpost'],
    recommendedCraft: 'Nebula Starchaser / Aegis Crawler',
    theme: {
      skyTop: '#030d17',
      skyBottom: '#071b2d',
      terrainFill: '#0a1d30',
      terrainBorder: '#67e8f9',
      terrainAccent: '#a5f3fc',
      gridColor: 'rgba(103, 232, 249, 0.07)',
      dustColor: '#cffafe',
      starDensity: 140,
      glowColor: 'rgba(103, 232, 249, 0.3)',
    },
    seed: 33719,
    targetTimeSec: 195,
    difficulty: 'Hard',
  },

  // =========================================================================
  // 3. LARGE PLANETS (Vast Caverns, Multi-Tier Hubs, Vehicle & Rover Logistics)
  // =========================================================================
  {
    id: 'vespera',
    name: 'Vespera Heavy',
    sizeCategory: 'Large',
    category: 'High-Mass Super Earth',
    description: 'Crushing gravity. Transport a 650kg Heavy Fusion Reactor Core between deep basalt chambers without structural cable failure.',
    gravity: 7.20,
    airResistance: 0.0015,
    fuelBurnRate: 6.8,
    surfacePressureBar: 2.80,
    surfaceTempC: 85,
    radiationRadPerHr: 14.8,
    windSpeedKmh: 65,
    hazards: ['Severe 7.2g Crushing Gravity', 'Rapid Fuel Depletion on Hover', 'Tether High-Tension Cable Snap Risk'],
    objectives: ['Execute High-Thrust Liftoff', 'Extract 650kg Heavy Fusion Reactor', 'Maneuver Heavy Load through Basalt Gaps', 'Touchdown on Reinforced Pad Alpha'],
    recommendedCraft: 'Titan Behemoth / Goliath Carrier / Mammoth Rig',
    theme: {
      skyTop: '#140c03',
      skyBottom: '#281704',
      terrainFill: '#211303',
      terrainBorder: '#f59e0b',
      terrainAccent: '#ef4444',
      gridColor: 'rgba(245, 158, 11, 0.08)',
      dustColor: '#fde68a',
      starDensity: 130,
      glowColor: 'rgba(245, 158, 11, 0.35)',
    },
    seed: 94811,
    targetTimeSec: 400,
    difficulty: 'Extreme',
  },
  {
    id: 'calypso',
    name: 'Calypso Caldera',
    sizeCategory: 'Large',
    category: 'Geothermal Magma Cavern',
    description: 'Expansive volcanic rift filled with superheated thermal columns, hanging basalt stalactites, and active lava chimneys. High updrafts require active counter-thrust.',
    gravity: 4.80,
    airResistance: 0.0018,
    fuelBurnRate: 6.2,
    surfacePressureBar: 1.85,
    surfaceTempC: 340,
    radiationRadPerHr: 35.0,
    windSpeedKmh: 82,
    hazards: ['Superheated Magma Fissures', 'Severe Thermal Updraft Buffeting', 'Collapsing Ash Columns'],
    objectives: ['Navigate Magma Rift Valley', 'Load Heavy Exploration Rover from Depot', 'Transport Rover to Caldera Lab 3', 'Land on Primary Geothermal Hub'],
    recommendedCraft: 'Goliath Carrier / Behemoth-IX / Valkyrie',
    theme: {
      skyTop: '#1a0505',
      skyBottom: '#340808',
      terrainFill: '#2c0606',
      terrainBorder: '#ef4444',
      terrainAccent: '#f97316',
      gridColor: 'rgba(239, 68, 68, 0.08)',
      dustColor: '#fca5a5',
      starDensity: 90,
      glowColor: 'rgba(239, 68, 68, 0.4)',
    },
    seed: 62019,
    targetTimeSec: 220,
    difficulty: 'Hard',
  },
  {
    id: 'zephyr',
    name: 'Zephyr Tempest',
    sizeCategory: 'Large',
    category: 'High-Wind Storm Basin',
    description: 'Vast storm cavern with persistent high-velocity lateral jetstreams. Pilots must constantly counter horizontal drift while navigating stepped cavern corridors.',
    gravity: 2.80,
    airResistance: 0.0042,
    fuelBurnRate: 5.6,
    surfacePressureBar: 3.20,
    surfaceTempC: -15,
    radiationRadPerHr: 6.2,
    windSpeedKmh: 140,
    hazards: ['140 km/h Crosswind Jetstreams', 'Vortical Shear Zones', 'High Atmospheric Kinetic Drag'],
    objectives: ['Counter Heavy Crosswind Shear', 'Ferry Supply Pod across Storm Gorge', 'Land on Wind-Shielded Recovery Deck'],
    recommendedCraft: 'Nebula Starchaser / Valkyrie Dropship',
    theme: {
      skyTop: '#021818',
      skyBottom: '#052c2c',
      terrainFill: '#042222',
      terrainBorder: '#14b8a6',
      terrainAccent: '#5eead4',
      gridColor: 'rgba(20, 184, 166, 0.08)',
      dustColor: '#99f6e4',
      starDensity: 110,
      glowColor: 'rgba(20, 184, 166, 0.35)',
    },
    seed: 83105,
    targetTimeSec: 240,
    difficulty: 'Hard',
  },
  {
    id: 'tartarus',
    name: 'Tartarus Nexus',
    sizeCategory: 'Large',
    category: 'Deep Industrial Mining Citadel',
    description: 'Multi-layer underground industrial refinery with 3 distinct elevator shafts, heavy robotic gantries, and dual vehicle transport depots.',
    gravity: 5.40,
    airResistance: 0.0012,
    fuelBurnRate: 6.4,
    surfacePressureBar: 2.10,
    surfaceTempC: 62,
    radiationRadPerHr: 18.5,
    windSpeedKmh: 40,
    hazards: ['Multi-Deck Steel Truss Infrastructure', 'High-Mass Industrial Vehicle Loading', 'Complex Multi-Platform Routing'],
    objectives: ['Deploy Ramp at Tartarus Vehicle Depot', 'Embark 12-Wheeler Planetary Rover', 'Transport & Deliver to Refinery Nexus', 'Touchdown on Heavy Recovery Pad'],
    recommendedCraft: 'Leviathan Titan / Goliath Carrier / Mammoth Rig',
    theme: {
      skyTop: '#0d0d17',
      skyBottom: '#181829',
      terrainFill: '#151524',
      terrainBorder: '#818cf8',
      terrainAccent: '#a5b4fc',
      gridColor: 'rgba(129, 140, 248, 0.07)',
      dustColor: '#c7d2fe',
      starDensity: 125,
      glowColor: 'rgba(129, 140, 248, 0.35)',
    },
    seed: 74902,
    targetTimeSec: 260,
    difficulty: 'Hard',
  },

  // =========================================================================
  // 4. VERY LARGE PLANETS (Colossal Mega-Caverns, Multi-Objective Relays)
  // =========================================================================
  {
    id: 'hyperion',
    name: 'Hyperion Mega-Cavern',
    sizeCategory: 'Very Large',
    category: 'Colossal 4-Tier Spire Labyrinth',
    description: 'An immense subterranean expanse stretching across 14 kilometers of interconnected cave chambers, towering crystal spires, and multiple cargo extraction points.',
    gravity: 3.10,
    airResistance: 0.0016,
    fuelBurnRate: 5.8,
    surfacePressureBar: 1.60,
    surfaceTempC: -28,
    radiationRadPerHr: 8.5,
    windSpeedKmh: 55,
    hazards: ['Gigantic 14km Expansive Vaults', 'Multiple Branching Dead-End Chasms', 'Fuel Starvation Risk on Long Transits'],
    objectives: ['Navigate Upper Crystal Spire Vault', 'Extract Heavy Xenon Container from Level 4', 'Refuel at Intermediate Depots', 'Complete 14km Long-Range Expedition'],
    recommendedCraft: 'Orion Surveyor / Vanguard Exoship / Juggernaut',
    theme: {
      skyTop: '#080c18',
      skyBottom: '#101a30',
      terrainFill: '#0d1526',
      terrainBorder: '#38bdf8',
      terrainAccent: '#818cf8',
      gridColor: 'rgba(56, 189, 248, 0.07)',
      dustColor: '#bae6fd',
      starDensity: 210,
      glowColor: 'rgba(56, 189, 248, 0.35)',
    },
    seed: 99104,
    targetTimeSec: 320,
    difficulty: 'Extreme',
  },
  {
    id: 'promethean',
    name: 'Promethean Core',
    sizeCategory: 'Very Large',
    category: 'Supermassive Volcanic Rift',
    description: 'A gigantic 15km supermassive volcanic rift featuring multi-stage sinking basalt shafts, intense convective updrafts, and two separate vehicle loading bays.',
    gravity: 6.20,
    airResistance: 0.0022,
    fuelBurnRate: 7.2,
    surfacePressureBar: 3.60,
    surfaceTempC: 380,
    radiationRadPerHr: 42.0,
    windSpeedKmh: 95,
    hazards: ['Extreme Thermal Shock', 'Crushing 6.2g Heavy Gravity Well', 'Dual-Rover Transport Logistics'],
    objectives: ['Descend into Core Fissure Level 5', 'Load Heavy Mining Excavator Truck', 'Ascend through Narrow Basalt Shaft', 'Deliver Cargo to Surface Bastion'],
    recommendedCraft: 'Juggernaut Lifter / Behemoth-IX / Titan Behemoth',
    theme: {
      skyTop: '#190a02',
      skyBottom: '#321404',
      terrainFill: '#291003',
      terrainBorder: '#ea580c',
      terrainAccent: '#fb923c',
      gridColor: 'rgba(234, 88, 12, 0.08)',
      dustColor: '#fed7aa',
      starDensity: 130,
      glowColor: 'rgba(234, 88, 12, 0.4)',
    },
    seed: 58213,
    targetTimeSec: 340,
    difficulty: 'Extreme',
  },
  {
    id: 'abyssus',
    name: 'Abyssus Void',
    sizeCategory: 'Very Large',
    category: 'Deep Void Canyon & S-Tunnels',
    description: 'A cavernous 15.5km deep void chasm containing 5 distinct subterranean strata, floating magnetic monoliths, and severe descending drafts.',
    gravity: 2.45,
    airResistance: 0.0028,
    fuelBurnRate: 5.5,
    surfacePressureBar: 2.20,
    surfaceTempC: -90,
    radiationRadPerHr: 15.0,
    windSpeedKmh: 78,
    hazards: ['Complex 5-Tier Strata Topography', 'Narrow Magnetic S-Curve Choke-points', 'Long Distance Inertial Drift'],
    objectives: ['Navigate Full 5-Tier Subterranean Maze', 'Secure Both Isotope Core & Scientific Sensors', 'Deliver to Void Research Outpost'],
    recommendedCraft: 'Vanguard Exoship / Orion Surveyor / Leviathan Titan',
    theme: {
      skyTop: '#0d0417',
      skyBottom: '#1c0832',
      terrainFill: '#17062a',
      terrainBorder: '#d946ef',
      terrainAccent: '#f0abfc',
      gridColor: 'rgba(217, 70, 239, 0.07)',
      dustColor: '#f5d0fe',
      starDensity: 230,
      glowColor: 'rgba(217, 70, 239, 0.35)',
    },
    seed: 61928,
    targetTimeSec: 360,
    difficulty: 'Extreme',
  },
  {
    id: 'omega',
    name: 'Omega Prime Citadel',
    sizeCategory: 'Very Large',
    category: 'Grand Sector 9 Deep Fortress',
    description: 'The ultimate piloting challenge: a 16km mega-citadel subterranean fortress with 8.4g gravity, multi-tier defense gates, dual cargo bays, and heavy rover transport requirements.',
    gravity: 8.40,
    airResistance: 0.0035,
    fuelBurnRate: 8.5,
    surfacePressureBar: 4.20,
    surfaceTempC: 110,
    radiationRadPerHr: 50.0,
    windSpeedKmh: 110,
    hazards: ['Brutal 8.4g High-Mass Gravity', 'Multi-Deck Armored Citadel Walls', 'Dual Cargo & Vehicle Transporter Relay', 'Narrow Gateway Clearances'],
    objectives: ['Launch from Omega Bastion Deck', 'Load Armored Goliath Rover from Depot 1', 'Transport Rover to Omega Central Reactor', 'Extract Primary Fusion Node & Touchdown on LZ'],
    recommendedCraft: 'Juggernaut Lifter / Leviathan Titan / Goliath Carrier',
    theme: {
      skyTop: '#051119',
      skyBottom: '#0a2333',
      terrainFill: '#081d2b',
      terrainBorder: '#06b6d4',
      terrainAccent: '#67e8f9',
      gridColor: 'rgba(6, 182, 212, 0.08)',
      dustColor: '#a5f3fc',
      starDensity: 250,
      glowColor: 'rgba(6, 182, 212, 0.4)',
    },
    seed: 99999,
    targetTimeSec: 380,
    difficulty: 'Extreme',
  },
];

export function createCustomPlanet(seed: number, gravity: number, difficulty: 'Easy' | 'Medium' | 'Hard' | 'Extreme'): PlanetConfig {
  const themes = [
    {
      skyTop: '#080c14',
      skyBottom: '#101726',
      terrainFill: '#141d2f',
      terrainBorder: '#60a5fa',
      terrainAccent: '#93c5fd',
      gridColor: 'rgba(96, 165, 250, 0.06)',
      dustColor: '#bfdbfe',
      starDensity: 150,
      glowColor: 'rgba(96, 165, 250, 0.3)',
    },
    {
      skyTop: '#100814',
      skyBottom: '#22102b',
      terrainFill: '#1f0f26',
      terrainBorder: '#f472b6',
      terrainAccent: '#ec4899',
      gridColor: 'rgba(244, 114, 182, 0.06)',
      dustColor: '#fbcfe8',
      starDensity: 140,
      glowColor: 'rgba(244, 114, 182, 0.3)',
    },
    {
      skyTop: '#08140f',
      skyBottom: '#102b21',
      terrainFill: '#0e261d',
      terrainBorder: '#4ade80',
      terrainAccent: '#22c55e',
      gridColor: 'rgba(74, 222, 128, 0.06)',
      dustColor: '#bbf7d0',
      starDensity: 120,
      glowColor: 'rgba(74, 222, 128, 0.3)',
    },
  ];

  const theme = themes[Math.abs(seed) % themes.length];

  return {
    id: `custom-${seed}`,
    name: `Sector-${(seed % 900 + 100)}`,
    category: 'Procedural Expedition',
    sizeCategory: 'Medium',
    width: 8600,
    height: 3200,
    description: `Expedition world with gravity ${gravity.toFixed(2)} m/s² and procedurally shaped subterranean cave systems.`,
    gravity,
    airResistance: gravity > 5 ? 0.0012 : gravity < 1.5 ? 0.0001 : 0.0005,
    fuelBurnRate: 4.5 + gravity * 0.35,
    surfacePressureBar: Number((gravity * 0.25).toFixed(2)),
    surfaceTempC: -40 + Math.round((seed % 100) * 1.5),
    radiationRadPerHr: Number((Math.abs(seed % 20) * 0.8).toFixed(1)),
    windSpeedKmh: Math.round(Math.abs(seed % 80)),
    hazards: ['Procedural Underground Formations', 'Variable Cavern Clearances', 'Dynamic Gravitational Sink'],
    objectives: ['Survey Unknown Subterranean Sector', 'Navigate Cavern Choke-points', 'Perform Precision Touchdown on LZ'],
    recommendedCraft: gravity > 5 ? 'Titan Behemoth / Goliath Carrier' : 'Apollo Recon / Aegis Crawler',
    theme,
    seed,
    targetTimeSec: 180,
    difficulty,
  };
}
