import { ShipModelConfig, ShipModelId } from '../types';

export const SHIPS: ShipModelConfig[] = [
  // =========================================================================
  // 1. SMALL RECON & RACING CRAFTS (Ultralight, High Agility, Precision Vector)
  // =========================================================================
  {
    id: 'viper',
    name: 'Viper Dart',
    codename: 'VX-7 Interceptor',
    tagline: 'Ultralight High-Agility Racing Dart',
    classType: 'Small Recon',
    description: 'A razor-thin, needle-nosed racing craft with blistering angular velocity and tight vector control. Low inertia requires delicate thruster taps to navigate narrow rock chutes.',
    width: 78,
    height: 94,
    renderScale: 1.4,
    maxFuel: 130,
    thrustMultiplier: 0.95,
    torqueMultiplier: 1.45,
    mass: 0.75,
    armor: 0.12,
    emptyMassTons: 4.2,
    maxThrustKn: 65,
    twr: 1.57,
    rcsResponseMs: 18,
    armorRatingMm: 25,
    cargoHookCapacityKg: 250,
    roverBayCapacity: 'None (Ultralight Hull)',
    propulsionType: 'Hypergolic Pulsed Ion-Plasma',
    operationalCeiling: 'Orbital Intercept & Slalom',
    manufactureOrigin: 'Apex Orbital Works (Ceres)',
    primaryColor: '#0f172a',
    accentColor: '#f43f5e',
    visorColor: '#ef4444',
    footpadSpan: 67.2,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -49.0 },
      leftShoulder: { x: -39.2, y: 29.4 },
      rightShoulder: { x: 39.2, y: 29.4 },
      leftHip: { x: -19.6, y: 33.6 },
      rightHip: { x: 19.6, y: 33.6 },
      leftFoot: { x: -33.6, y: 42.0 },
      rightFoot: { x: 33.6, y: 42.0 },
      leftThrusterPos: { x: -12.6, y: 35.0 },
      rightThrusterPos: { x: 12.6, y: 35.0 },
    },
    stats: {
      agility: 5,
      fuelTank: 2,
      stability: 2,
      thrust: 4,
      armor: 2,
    },
  },
  {
    id: 'wasp',
    name: 'Wasp Scout',
    codename: 'WS-2 Stinger',
    tagline: 'Dual-Pod Micro Recon Lander',
    classType: 'Small Recon',
    description: 'A compact, dual-outrigger scout designed for tight cavern exploration. Outfitted with twin vectoring pods and gold thermal foil wrapping for high radiation zones.',
    width: 80,
    height: 84,
    renderScale: 1.42,
    maxFuel: 145,
    thrustMultiplier: 1.05,
    torqueMultiplier: 1.35,
    mass: 0.82,
    armor: 0.20,
    emptyMassTons: 5.1,
    maxThrustKn: 78,
    twr: 1.55,
    rcsResponseMs: 24,
    armorRatingMm: 35,
    cargoHookCapacityKg: 300,
    roverBayCapacity: 'None (Compact Chassis)',
    propulsionType: 'Dual Hydrazine Vector Nozzles',
    operationalCeiling: 'Sub-surface Crevasses',
    manufactureOrigin: 'Stinger Aerospace (Ganymede)',
    primaryColor: '#1e293b',
    accentColor: '#eab308',
    visorColor: '#ca8a04',
    footpadSpan: 76.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -42.0 },
      leftShoulder: { x: -38.0, y: -6.0 },
      rightShoulder: { x: 38.0, y: -6.0 },
      leftHip: { x: -28.0, y: 28.0 },
      rightHip: { x: 28.0, y: 28.0 },
      leftFoot: { x: -34.08, y: 39.76 },
      rightFoot: { x: 34.08, y: 39.76 },
      leftThrusterPos: { x: -22.0, y: 34.0 },
      rightThrusterPos: { x: 22.0, y: 34.0 },
    },
    stats: {
      agility: 5,
      fuelTank: 3,
      stability: 3,
      thrust: 4,
      armor: 2,
    },
  },
  {
    id: 'kestrel',
    name: 'Kestrel Stunt',
    codename: 'KS-9 Aerobatic Dart',
    tagline: 'Delta-Wing Acrobat Lander',
    classType: 'Small Recon',
    description: 'Equipped with forward swept canards and titanium skid plates. Exceptional rotational response allows for inverted flips and rapid descent corrections.',
    width: 82,
    height: 86,
    renderScale: 1.44,
    maxFuel: 150,
    thrustMultiplier: 1.08,
    torqueMultiplier: 1.40,
    mass: 0.85,
    armor: 0.22,
    emptyMassTons: 5.6,
    maxThrustKn: 85,
    twr: 1.54,
    rcsResponseMs: 20,
    armorRatingMm: 40,
    cargoHookCapacityKg: 350,
    roverBayCapacity: 'None (Acrobatic Frame)',
    propulsionType: 'Cryo-Methane Turbopump',
    operationalCeiling: 'Planetary Slopes & Mesas',
    manufactureOrigin: 'Veloce Dynamic Labs (Europa)',
    primaryColor: '#0f172a',
    accentColor: '#06b6d4',
    visorColor: '#0284c7',
    footpadSpan: 78.5,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -45.0 },
      leftShoulder: { x: -39.0, y: 15.0 },
      rightShoulder: { x: 39.0, y: 15.0 },
      leftHip: { x: -26.0, y: 30.0 },
      rightHip: { x: 26.0, y: 30.0 },
      leftFoot: { x: -36.0, y: 40.32 },
      rightFoot: { x: 36.0, y: 40.32 },
      leftThrusterPos: { x: -18.0, y: 34.5 },
      rightThrusterPos: { x: 18.0, y: 34.5 },
    },
    stats: {
      agility: 5,
      fuelTank: 3,
      stability: 3,
      thrust: 4,
      armor: 3,
    },
  },
  {
    id: 'spectre',
    name: 'Spectre Recon',
    codename: 'SP-4 Stealth Surveyor',
    tagline: 'Carbon-Nanotube Silent Surveyor',
    classType: 'Small Recon',
    description: 'Forged with radar-absorbent matte carbon composites and micro-pulsed cold-gas RCS jets. Glides with minimal turbulence through subterranean draft shafts.',
    width: 80,
    height: 88,
    renderScale: 1.45,
    maxFuel: 155,
    thrustMultiplier: 1.02,
    torqueMultiplier: 1.25,
    mass: 0.88,
    armor: 0.28,
    emptyMassTons: 6.0,
    maxThrustKn: 88,
    twr: 1.49,
    rcsResponseMs: 22,
    armorRatingMm: 50,
    cargoHookCapacityKg: 400,
    roverBayCapacity: 'None (Stealth Monocoque)',
    propulsionType: 'Cold-Gas / Xenon Hybrid Core',
    operationalCeiling: 'Deep Cavern Fissures',
    manufactureOrigin: 'Shadowline Orbital (Titan)',
    primaryColor: '#090d16',
    accentColor: '#a855f7',
    visorColor: '#7e22ce',
    footpadSpan: 80.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -44.0 },
      leftShoulder: { x: -36.0, y: -4.0 },
      rightShoulder: { x: 36.0, y: -4.0 },
      leftHip: { x: -28.0, y: 30.0 },
      rightHip: { x: 28.0, y: 30.0 },
      leftFoot: { x: -37.7, y: 42.05 },
      rightFoot: { x: 37.7, y: 42.05 },
      leftThrusterPos: { x: -20.0, y: 35.0 },
      rightThrusterPos: { x: 20.0, y: 35.0 },
    },
    stats: {
      agility: 4,
      fuelTank: 3,
      stability: 4,
      thrust: 4,
      armor: 3,
    },
  },
  {
    id: 'apollo',
    name: 'Apollo Recon',
    codename: 'LM-Scout Mk IV',
    tagline: 'Standard Balanced Recon Lander',
    classType: 'Small Recon',
    description: 'A finely tuned, all-purpose exploration lander with balanced handling, reliable fuel reserves, gold thermal quilting, and responsive reaction thrusters.',
    width: 82,
    height: 88,
    renderScale: 1.45,
    maxFuel: 160,
    thrustMultiplier: 1.0,
    torqueMultiplier: 1.0,
    mass: 1.0,
    armor: 0.25,
    emptyMassTons: 7.2,
    maxThrustKn: 95,
    twr: 1.34,
    rcsResponseMs: 30,
    armorRatingMm: 45,
    cargoHookCapacityKg: 500,
    roverBayCapacity: 'Light Scientific Gear Only',
    propulsionType: 'Aerozine-50 / NTO Bipropellant',
    operationalCeiling: 'All Planetary Regimes',
    manufactureOrigin: 'Lunar Surface Systems (Luna)',
    primaryColor: '#f8fafc',
    accentColor: '#38bdf8',
    visorColor: '#0284c7',
    footpadSpan: 81.2,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -39.15 },
      leftShoulder: { x: -30.45, y: -7.25 },
      rightShoulder: { x: 30.45, y: -7.25 },
      leftHip: { x: -27.55, y: 31.9 },
      rightHip: { x: 27.55, y: 31.9 },
      leftFoot: { x: -40.6, y: 43.5 },
      rightFoot: { x: 40.6, y: 43.5 },
      leftThrusterPos: { x: -19.58, y: 35.53 },
      rightThrusterPos: { x: 19.58, y: 35.53 },
    },
    stats: {
      agility: 4,
      fuelTank: 3,
      stability: 4,
      thrust: 3,
      armor: 3,
    },
  },

  // =========================================================================
  // 2. MEDIUM EXPLORER & TACTICAL CRAFTS (Extended Range, Multi-Thruster, Heavy Gear)
  // =========================================================================
  {
    id: 'aegis',
    name: 'Aegis Crawler',
    codename: 'SRV-Lunar Surveyor',
    tagline: 'Low-Slung Surface Research Platform',
    classType: 'Medium Explorer',
    description: 'An ultra-wide, low-profile science pod featuring reinforced hydraulic outrigger landing gear that excels at stable, low-impact descents onto uneven terrain.',
    width: 102,
    height: 87,
    renderScale: 1.55,
    maxFuel: 190,
    thrustMultiplier: 1.1,
    torqueMultiplier: 0.95,
    mass: 1.15,
    armor: 0.45,
    emptyMassTons: 9.8,
    maxThrustKn: 130,
    twr: 1.35,
    rcsResponseMs: 38,
    armorRatingMm: 80,
    cargoHookCapacityKg: 650,
    roverBayCapacity: 'Survey Rig Attachment Deck',
    propulsionType: 'Staged Combustion Hydrolox',
    operationalCeiling: 'Rugged Surface Basins',
    manufactureOrigin: 'Aegis Heavy Systems (Phobos)',
    primaryColor: '#cbd5e1',
    accentColor: '#10b981',
    visorColor: '#059669',
    footpadSpan: 102.3,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -38.75 },
      leftShoulder: { x: -38.75, y: -13.95 },
      rightShoulder: { x: 38.75, y: -13.95 },
      leftHip: { x: -38.75, y: 21.7 },
      rightHip: { x: 38.75, y: 21.7 },
      leftFoot: { x: -51.15, y: 43.4 },
      rightFoot: { x: 51.15, y: 43.4 },
      leftThrusterPos: { x: -20.93, y: 30.23 },
      rightThrusterPos: { x: 20.93, y: 30.23 },
    },
    stats: {
      agility: 3,
      fuelTank: 4,
      stability: 5,
      thrust: 3,
      armor: 5,
    },
  },
  {
    id: 'nebula',
    name: 'Nebula Starchaser',
    codename: 'NX-Cosmos Delta',
    tagline: 'Atmospheric Delta Cruiser',
    classType: 'Medium Explorer',
    description: 'Features swept aerodynamic carbon-nanotube wings and dual vectoring plasma exhausts. Glides smoothly through atmospheric drafts and high crosswinds.',
    width: 87,
    height: 86,
    renderScale: 1.5,
    maxFuel: 180,
    thrustMultiplier: 1.15,
    torqueMultiplier: 1.2,
    mass: 0.95,
    armor: 0.20,
    emptyMassTons: 8.4,
    maxThrustKn: 120,
    twr: 1.45,
    rcsResponseMs: 25,
    armorRatingMm: 45,
    cargoHookCapacityKg: 550,
    roverBayCapacity: 'None (Aero Wing Structure)',
    propulsionType: 'Dual Aerospike Rocket Exhausts',
    operationalCeiling: 'Dense Gas & Vapor Atmospheres',
    manufactureOrigin: 'Cosmos Astroworks (Titan)',
    primaryColor: '#f1f5f9',
    accentColor: '#8b5cf6',
    visorColor: '#7c3aed',
    footpadSpan: 72.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -37.5 },
      leftShoulder: { x: -43.5, y: -21.0 },
      rightShoulder: { x: 43.5, y: -21.0 },
      leftHip: { x: -40.5, y: 34.5 },
      rightHip: { x: 40.5, y: 34.5 },
      leftFoot: { x: -36.0, y: 45.0 },
      rightFoot: { x: 36.0, y: 45.0 },
      leftThrusterPos: { x: -31.5, y: 33.0 },
      rightThrusterPos: { x: 31.5, y: 33.0 },
    },
    stats: {
      agility: 4,
      fuelTank: 4,
      stability: 4,
      thrust: 4,
      armor: 3,
    },
  },
  {
    id: 'vanguard',
    name: 'Vanguard Exoship',
    codename: 'VG-Exo Crusader',
    tagline: 'Multi-Stage Deep Core Explorer',
    classType: 'Medium Explorer',
    description: 'A towering, multi-module deep space cruiser wrapped in gold thermal foil with quad landing stabilizers and high-efficiency auxiliary booster tanks.',
    width: 87,
    height: 102,
    renderScale: 1.55,
    maxFuel: 220,
    thrustMultiplier: 1.25,
    torqueMultiplier: 1.05,
    mass: 1.2,
    armor: 0.35,
    emptyMassTons: 11.2,
    maxThrustKn: 165,
    twr: 1.50,
    rcsResponseMs: 32,
    armorRatingMm: 70,
    cargoHookCapacityKg: 750,
    roverBayCapacity: 'Modular Equipment Container',
    propulsionType: 'Nuclear Thermal Closed-Cycle Gas Core',
    operationalCeiling: 'Interplanetary Outer Reaches',
    manufactureOrigin: 'Vanguard Orbital Yards (Mars)',
    primaryColor: '#f8fafc',
    accentColor: '#eab308',
    visorColor: '#ca8a04',
    footpadSpan: 86.8,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -55.8 },
      leftShoulder: { x: -27.9, y: 3.1 },
      rightShoulder: { x: 27.9, y: 3.1 },
      leftHip: { x: -27.9, y: 29.45 },
      rightHip: { x: 27.9, y: 29.45 },
      leftFoot: { x: -43.4, y: 43.4 },
      rightFoot: { x: 43.4, y: 43.4 },
      leftThrusterPos: { x: -19.38, y: 34.1 },
      rightThrusterPos: { x: 19.38, y: 34.1 },
    },
    stats: {
      agility: 3,
      fuelTank: 5,
      stability: 4,
      thrust: 5,
      armor: 4,
    },
  },
  {
    id: 'orion',
    name: 'Orion Surveyor',
    codename: 'OR-300 Deep Space Scout',
    tagline: 'Twin-Boom Long-Range Science Vessel',
    classType: 'Medium Explorer',
    description: 'Equipped with twin sensor booms, high-output fuel reserves, and multi-spectral spectrometers. Delivers exceptional stability in complex magnetic cavern anomalies.',
    width: 92,
    height: 90,
    renderScale: 1.52,
    maxFuel: 210,
    thrustMultiplier: 1.18,
    torqueMultiplier: 1.10,
    mass: 1.10,
    armor: 0.32,
    emptyMassTons: 10.5,
    maxThrustKn: 145,
    twr: 1.41,
    rcsResponseMs: 28,
    armorRatingMm: 65,
    cargoHookCapacityKg: 700,
    roverBayCapacity: 'Sample Recovery Locker Deck',
    propulsionType: 'Magnetoplasmadynamic Vector Core',
    operationalCeiling: 'Deep Planetary Interior Chasms',
    manufactureOrigin: 'Orion Stellar Consortium (Vesta)',
    primaryColor: '#0f172a',
    accentColor: '#38bdf8',
    visorColor: '#0369a1',
    footpadSpan: 88.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -45.0 },
      leftShoulder: { x: -44.0, y: -10.0 },
      rightShoulder: { x: 44.0, y: -10.0 },
      leftHip: { x: -32.0, y: 28.0 },
      rightHip: { x: 32.0, y: 28.0 },
      leftFoot: { x: -42.56, y: 45.6 },
      rightFoot: { x: 42.56, y: 45.6 },
      leftThrusterPos: { x: -24.0, y: 34.0 },
      rightThrusterPos: { x: 24.0, y: 34.0 },
    },
    stats: {
      agility: 4,
      fuelTank: 4,
      stability: 4,
      thrust: 4,
      armor: 4,
    },
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie Tactical',
    codename: 'VK-55 Armored Dropship',
    tagline: 'Reinforced Combat Dropship',
    classType: 'Medium Explorer',
    description: 'Armored titanium hull plating with quad gimbal nozzles. Built to withstand high-velocity rock collisions and turbulent geothermal venting.',
    width: 96,
    height: 92,
    renderScale: 1.54,
    maxFuel: 200,
    thrustMultiplier: 1.28,
    torqueMultiplier: 1.05,
    mass: 1.25,
    armor: 0.52,
    emptyMassTons: 12.0,
    maxThrustKn: 175,
    twr: 1.48,
    rcsResponseMs: 34,
    armorRatingMm: 110,
    cargoHookCapacityKg: 800,
    roverBayCapacity: 'Reinforced Tactical Pod Deck',
    propulsionType: 'Quad Quad-Chamber Methalox Thrust Array',
    operationalCeiling: 'Hostile Thermal & Debris Zones',
    manufactureOrigin: 'Valhalla Defense Yards (Vespera)',
    primaryColor: '#1e293b',
    accentColor: '#ef4444',
    visorColor: '#b91c1c',
    footpadSpan: 94.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -46.0 },
      leftShoulder: { x: -45.0, y: 5.0 },
      rightShoulder: { x: 45.0, y: 5.0 },
      leftHip: { x: -35.0, y: 28.0 },
      rightHip: { x: 35.0, y: 28.0 },
      leftFoot: { x: -46.2, y: 47.74 },
      rightFoot: { x: 46.2, y: 47.74 },
      leftThrusterPos: { x: -26.0, y: 34.0 },
      rightThrusterPos: { x: 26.0, y: 34.0 },
    },
    stats: {
      agility: 3,
      fuelTank: 4,
      stability: 4,
      thrust: 5,
      armor: 5,
    },
  },

  // =========================================================================
  // 3. HEAVY INDUSTRIAL TRANSPORTS & ROVER CARRIERS (Vehicles, Ramps, Heavy Bays)
  // =========================================================================
  {
    id: 'titan',
    name: 'Titan Behemoth',
    codename: 'HC-9000 Dreadnought',
    tagline: 'Heavy Industrial Cargo Hauler',
    classType: 'Heavy Transport',
    description: 'An ultra-wide, heavily armored freight vessel equipped with massive high-capacity fuel tanks, high-torque twin gimbals, and vehicle transport capability.',
    width: 126,
    height: 100,
    renderScale: 1.85,
    maxFuel: 260,
    thrustMultiplier: 1.35,
    torqueMultiplier: 0.85,
    mass: 1.35,
    armor: 0.50,
    emptyMassTons: 16.5,
    maxThrustKn: 240,
    twr: 1.48,
    rcsResponseMs: 45,
    armorRatingMm: 120,
    cargoHookCapacityKg: 1200,
    roverBayCapacity: 'Full Heavy Rover Transport Deck',
    propulsionType: 'Dual Heavy Gimballed Hydrolox Engines',
    operationalCeiling: 'High-Gravity Freight Transport',
    manufactureOrigin: 'Titan Industrial Shipworks (Titan)',
    primaryColor: '#e2e8f0',
    accentColor: '#f59e0b',
    visorColor: '#ea580c',
    footpadSpan: 120.3,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 0, y: -40.7 },
      leftShoulder: { x: -62.9, y: 3.7 },
      rightShoulder: { x: 62.9, y: 3.7 },
      leftHip: { x: -51.8, y: 33.3 },
      rightHip: { x: 51.8, y: 33.3 },
      leftFoot: { x: -64.75, y: 51.8 },
      rightFoot: { x: 64.75, y: 51.8 },
      leftThrusterPos: { x: -35.15, y: 41.63 },
      rightThrusterPos: { x: 35.15, y: 41.63 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'goliath',
    name: 'Goliath Carrier',
    codename: 'CT-950 Colossus Hauler',
    tagline: 'Ultra-Wide Heavy Vehicle & Rover Carrier',
    classType: 'Rover Transporter',
    description: 'A massive, wide-bodied planetary transporter equipped with hydraulic landing ramps, wide-span outriggers, and a pressurized interior hold for transporting heavy rovers and industrial trucks.',
    width: 127,
    height: 130,
    renderScale: 1.68,
    maxFuel: 340,
    thrustMultiplier: 1.45,
    torqueMultiplier: 0.78,
    mass: 1.65,
    armor: 0.60,
    emptyMassTons: 22.0,
    maxThrustKn: 320,
    twr: 1.48,
    rcsResponseMs: 50,
    armorRatingMm: 150,
    cargoHookCapacityKg: 2000,
    roverBayCapacity: 'Pressurized Dual Rover Ramp Bay',
    propulsionType: 'Quad Staged Plasma Thrusters + Lift Jets',
    operationalCeiling: 'Planetary Surface Base Logistics',
    manufactureOrigin: 'Colossus Heavy Transports (Luna)',
    primaryColor: '#f8fafc',
    accentColor: '#f59e0b',
    visorColor: '#0ea5e9',
    footpadSpan: 127.68,
    isHeavyVehicleCarrier: true,
    canCarryVehicles: true,
    localPoints: {
      nose: { x: -47.04, y: -70.56 },
      leftShoulder: { x: -60.48, y: -57.12 },
      rightShoulder: { x: 60.48, y: 8.4 },
      leftHip: { x: -60.48, y: 26.88 },
      rightHip: { x: 60.48, y: 26.88 },
      leftFoot: { x: -63.84, y: 53.76 },
      rightFoot: { x: 63.84, y: 53.76 },
      extraLeftFoot: { x: -26.88, y: 53.76 },
      extraRightFoot: { x: 26.88, y: 53.76 },
      leftThrusterPos: { x: -45.36, y: 32.76 },
      rightThrusterPos: { x: 43.68, y: 32.76 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'behemoth',
    name: 'Behemoth-IX',
    codename: 'BH-900 Dreadnought',
    tagline: 'Massive Asymmetric Industrial Hauler',
    classType: 'Rover Transporter',
    description: 'A monstrous industrial transport featuring an offset starboard command bridge, a portside heavy cargo gantry truss, and a forward hydraulic ramp for loading heavy planetary vehicles.',
    width: 127,
    height: 133,
    renderScale: 1.68,
    maxFuel: 360,
    thrustMultiplier: 1.5,
    torqueMultiplier: 0.72,
    mass: 1.75,
    armor: 0.65,
    emptyMassTons: 25.4,
    maxThrustKn: 360,
    twr: 1.45,
    rcsResponseMs: 55,
    armorRatingMm: 175,
    cargoHookCapacityKg: 2500,
    roverBayCapacity: 'Asymmetric Heavy Vehicle Crane Ramp',
    propulsionType: 'Offset Dual-Chamber Fusion Torch Nozzles',
    operationalCeiling: 'Deep Mine Shaft Haulage',
    manufactureOrigin: 'Ironclad Heavy Foundries (Ares)',
    primaryColor: '#e2e8f0',
    accentColor: '#f97316',
    visorColor: '#0284c7',
    footpadSpan: 127.68,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 47.04, y: -72.24 },
      leftShoulder: { x: -60.48, y: -40.32 },
      rightShoulder: { x: 60.48, y: -57.12 },
      leftHip: { x: -60.48, y: 26.88 },
      rightHip: { x: 60.48, y: 26.88 },
      leftFoot: { x: -63.84, y: 55.44 },
      rightFoot: { x: 63.84, y: 55.44 },
      extraLeftFoot: { x: -25.2, y: 55.44 },
      extraRightFoot: { x: 25.2, y: 55.44 },
      leftThrusterPos: { x: -40.32, y: 32.76 },
      rightThrusterPos: { x: 43.68, y: 32.76 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'leviathan',
    name: 'Leviathan Titan',
    codename: 'LV-880 Split-Hull Carrier',
    tagline: 'Asymmetric Twin-Hull Supercarrier',
    classType: 'Rover Transporter',
    description: 'An immense asymmetric catamaran supercarrier with a heavy armored vehicle hangar on the port sponson, an offset starboard sensor spine, and an articulated hydraulic ramp door.',
    width: 140,
    height: 141,
    renderScale: 1.75,
    maxFuel: 380,
    thrustMultiplier: 1.55,
    torqueMultiplier: 0.70,
    mass: 1.85,
    armor: 0.70,
    emptyMassTons: 28.5,
    maxThrustKn: 410,
    twr: 1.47,
    rcsResponseMs: 58,
    armorRatingMm: 190,
    cargoHookCapacityKg: 3000,
    roverBayCapacity: 'Catamaran Dual-Sponson Heavy Hangar',
    propulsionType: 'Triple High-Volume Deuterium Jets',
    operationalCeiling: 'Planetary Citadel Logistics',
    manufactureOrigin: 'Leviathan Oceanic Orbital (Europa)',
    primaryColor: '#0f172a',
    accentColor: '#06b6d4',
    visorColor: '#38bdf8',
    footpadSpan: 140.0,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 38.5, y: -77.0 },
      leftShoulder: { x: -66.5, y: -49.0 },
      rightShoulder: { x: 66.5, y: -28.0 },
      leftHip: { x: -66.5, y: 28.0 },
      rightHip: { x: 66.5, y: 28.0 },
      leftFoot: { x: -70.0, y: 59.5 },
      rightFoot: { x: 70.0, y: 59.5 },
      extraLeftFoot: { x: -26.25, y: 59.5 },
      extraRightFoot: { x: 26.25, y: 59.5 },
      leftThrusterPos: { x: -42.0, y: 34.13 },
      rightThrusterPos: { x: 49.0, y: 34.13 },
    },
    stats: {
      agility: 1,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'mammoth',
    name: 'Mammoth Rig',
    codename: 'MR-700 Excavator Carrier',
    tagline: 'Heavy Logistics Mobile Base Carrier',
    classType: 'Rover Transporter',
    description: 'A formidable deep-mining transport equipped with a portside hydraulic crane boom, offset starboard fuel refinery columns, and an ultra-wide planetary crawler ramp bay.',
    width: 127,
    height: 119,
    renderScale: 1.68,
    maxFuel: 360,
    thrustMultiplier: 1.48,
    torqueMultiplier: 0.74,
    mass: 1.80,
    armor: 0.68,
    emptyMassTons: 26.8,
    maxThrustKn: 390,
    twr: 1.46,
    rcsResponseMs: 56,
    armorRatingMm: 180,
    cargoHookCapacityKg: 2800,
    roverBayCapacity: 'Heavy Mobile Base Ramp & Crane Bay',
    propulsionType: 'Refinery Fed Thermal Rocket Array',
    operationalCeiling: 'Deep Volcanic & Mining Rifts',
    manufactureOrigin: 'Mammoth Core Engineering (Tartarus)',
    primaryColor: '#334155',
    accentColor: '#eab308',
    visorColor: '#e11d48',
    footpadSpan: 127.68,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 57.12, y: -57.12 },
      leftShoulder: { x: -63.84, y: -47.04 },
      rightShoulder: { x: 63.84, y: -57.12 },
      leftHip: { x: -63.84, y: 26.88 },
      rightHip: { x: 63.84, y: 26.88 },
      leftFoot: { x: -63.84, y: 57.12 },
      rightFoot: { x: 63.84, y: 57.12 },
      extraLeftFoot: { x: -25.2, y: 57.12 },
      extraRightFoot: { x: 25.2, y: 57.12 },
      leftThrusterPos: { x: -40.32, y: 32.76 },
      rightThrusterPos: { x: 45.36, y: 32.76 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'juggernaut',
    name: 'Juggernaut Lifter',
    codename: 'JG-1200 Planetary Heavy Lifter',
    tagline: 'Quad-Engine Super-Heavy Rover Carrier',
    classType: 'Rover Transporter',
    description: 'The pinnacle of heavy surface logistics: equipped with quad gimballed rocket thrusters, reinforced tungsten landing outriggers, and dual drive-through hydraulic vehicle ramps.',
    width: 144,
    height: 140,
    renderScale: 1.76,
    maxFuel: 420,
    thrustMultiplier: 1.62,
    torqueMultiplier: 0.68,
    mass: 2.05,
    armor: 0.75,
    emptyMassTons: 32.0,
    maxThrustKn: 480,
    twr: 1.52,
    rcsResponseMs: 62,
    armorRatingMm: 220,
    cargoHookCapacityKg: 3500,
    roverBayCapacity: 'Dual Drive-Through Heavy Rover Ramp Hold',
    propulsionType: 'Quad Heavy Fusion Torch Combustion Array',
    operationalCeiling: 'Supermassive Gravity Worlds & Citadels',
    manufactureOrigin: 'Juggernaut Fleet Yards (Omega Prime)',
    primaryColor: '#0f172a',
    accentColor: '#10b981',
    visorColor: '#059669',
    footpadSpan: 142.0,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 0, y: -74.0 },
      leftShoulder: { x: -68.0, y: -45.0 },
      rightShoulder: { x: 68.0, y: -45.0 },
      leftHip: { x: -68.0, y: 28.0 },
      rightHip: { x: 68.0, y: 28.0 },
      leftFoot: { x: -79.2, y: 66.88 },
      rightFoot: { x: 79.2, y: 66.88 },
      extraLeftFoot: { x: -31.68, y: 66.88 },
      extraRightFoot: { x: 31.68, y: 66.88 },
      leftThrusterPos: { x: -46.0, y: 35.0 },
      rightThrusterPos: { x: 46.0, y: 35.0 },
    },
    stats: {
      agility: 1,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
];

export function getShipConfig(modelId: ShipModelId = 'apollo'): ShipModelConfig {
  return SHIPS.find((s) => s.id === modelId) || SHIPS[0];
}

export const SHIP_MODELS = SHIPS;
