import { ShipModelConfig, ShipModelId } from '../types';

export const SHIPS: ShipModelConfig[] = [
  // =========================================================================
  // 1. SMALL RECON & RACING CRAFTS (Ultralight, High Agility, Precision Vector)
  // =========================================================================
  {
    id: 'viper',
    name: 'Colonial Viper',
    codename: 'Mk II Interceptor',
    tagline: 'Colonial Fleet Starfighter',
    classType: 'Interceptor',
    description: 'The legendary Colonial Fleet starfighter — a fast, agile interceptor with a needle nose, broad delta wings and twin turbo-fusion engines. Its golden wing-root cannons and deep-blue faceted canopy are recognizable across the fleet.',
    width: 90,
    height: 95,
    renderScale: 1.4,
    maxFuel: 100,
    thrustMultiplier: 1.15,
    torqueMultiplier: 1.10,
    mass: 1.25,
    armor: 0.16,
    emptyMassTons: 6.8,
    maxThrustKn: 72,
    twr: 1.65,
    rcsResponseMs: 12,
    armorRatingMm: 30,
    cargoHookCapacityKg: 250,
    roverBayCapacity: 'None (Starfighter Hull)',
    propulsionType: 'Twin Turbo-Fusion Reaction Drives',
    operationalCeiling: 'Atmospheric & Space Intercept',
    manufactureOrigin: 'Colonial Fleet Yards (Ragnar Anchorage)',
    primaryColor: '#cbd5e1',
    accentColor: '#ef4444',
    visorColor: '#1e1b4b',
    footpadSpan: 61.6,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -53.2 },
      leftShoulder: { x: -44.8, y: -4.2 },
      rightShoulder: { x: 44.8, y: -4.2 },
      leftHip: { x: -26.0, y: 25.2 },
      rightHip: { x: 26.0, y: 25.2 },
      leftFoot: { x: -30.8, y: 41.3 },
      rightFoot: { x: 30.8, y: 41.3 },
      leftThrusterPos: { x: -18.9, y: 33.6 },
      rightThrusterPos: { x: 18.9, y: 33.6 },
    },
    stats: {
      agility: 4,
      fuelTank: 2,
      stability: 4,
      thrust: 4,
      armor: 3,
    },
  },
  {
    id: 'wasp',
    name: 'Wasp Heavy Fighter',
    codename: 'WS-3 Stinger',
    tagline: 'Armored Gunship Interceptor',
    classType: 'Heavy Fighter',
    description: 'A heavily armored gunship built around twin hull-mounted fusion torches and wing cannon pods. Sluggish in a turn but brutally durable, with a deep-space fuel reserve and a raised armor spine meant to shrug off hits that would shred lighter craft.',
    width: 102,
    height: 95,
    renderScale: 1.4,
    maxFuel: 120,
    thrustMultiplier: 1.4,
    torqueMultiplier: 0.9,
    mass: 2.2,
    armor: 0.35,
    emptyMassTons: 21.4,
    maxThrustKn: 168,
    twr: 1.62,
    rcsResponseMs: 34,
    armorRatingMm: 90,
    cargoHookCapacityKg: 150,
    roverBayCapacity: 'None (Armored Chassis)',
    propulsionType: 'Twin Heavy Fusion Torch Drives',
    operationalCeiling: 'High-Atmosphere & Orbital Strike',
    manufactureOrigin: 'Stinger Aerospace (Ganymede)',
    primaryColor: '#cbd5e1',
    accentColor: '#ea580c',
    visorColor: '#0f172a',
    footpadSpan: 67.2,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -53.2 },
      leftShoulder: { x: -42.0, y: -8.4 },
      rightShoulder: { x: 42.0, y: -8.4 },
      leftHip: { x: -18.2, y: 36.4 },
      rightHip: { x: 18.2, y: 36.4 },
      leftFoot: { x: -33.6, y: 41.3 },
      rightFoot: { x: 33.6, y: 41.3 },
      leftThrusterPos: { x: -13.3, y: 39.2 },
      rightThrusterPos: { x: 13.3, y: 39.2 },
    },
    stats: {
      agility: 3,
      fuelTank: 3,
      stability: 4,
      thrust: 5,
      armor: 5,
    },
  },  {
    id: 'kestrel',
    name: 'Kestrel Stunt',
    codename: 'KS-9 Aerobatic Dart',
    tagline: 'Delta-Wing Acrobat Lander',
    classType: 'Small Recon',
    description: 'Equipped with forward swept canards and titanium skid plates. Exceptional rotational response allows for inverted flips and rapid descent corrections.',
    width: 100,
    height: 96,
    renderScale: 1.4,
    maxFuel: 140,
    thrustMultiplier: 1.12,
    torqueMultiplier: 1.45,
    mass: 0.85,
    armor: 0.25,
    emptyMassTons: 5.4,
    maxThrustKn: 88,
    twr: 1.66,
    rcsResponseMs: 18,
    armorRatingMm: 45,
    cargoHookCapacityKg: 350,
    roverBayCapacity: 'None (Acrobatic Frame)',
    propulsionType: 'Cryo-Methane Turbopump',
    operationalCeiling: 'Planetary Slopes & Mesas',
    manufactureOrigin: 'Veloce Dynamic Labs (Europa)',
    primaryColor: '#0f172a',
    accentColor: '#06b6d4',
    visorColor: '#0284c7',
    footpadSpan: 67.2,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -53.2 },
      leftShoulder: { x: -49.0, y: 19.6 },
      rightShoulder: { x: 49.0, y: 19.6 },
      leftHip: { x: -24.5, y: 25.2 },
      rightHip: { x: 24.5, y: 25.2 },
      leftFoot: { x: -33.6, y: 41.3 },
      rightFoot: { x: 33.6, y: 41.3 },
      leftThrusterPos: { x: -18.2, y: 33.6 },
      rightThrusterPos: { x: 18.2, y: 33.6 },
    },
    stats: {
      agility: 5,
      fuelTank: 3,
      stability: 3,
      thrust: 4,
      armor: 3,
    },
  },
  {
    id: 'spectre',
    name: 'Spectre Transport',
    codename: 'SP-7 Shadow Transport',
    tagline: 'Stealth Personnel & Cargo Dropship',
    classType: 'Stealth Transport',
    description: 'Engineered with radar-absorbent matte carbon composites, wide multi-pane command bridge, rear clamshell loading ramp, and heavy-lift 2D vectoring nacelles for covert transport missions.',
    width: 98,
    height: 94,
    renderScale: 1.45,
    maxFuel: 180,
    thrustMultiplier: 1.18,
    torqueMultiplier: 1.05,
    mass: 1.25,
    armor: 0.35,
    emptyMassTons: 8.4,
    maxThrustKn: 120,
    twr: 1.45,
    rcsResponseMs: 24,
    armorRatingMm: 85,
    cargoHookCapacityKg: 1200,
    roverBayCapacity: 'Internal Clamshell Cargo Hold (12 m³)',
    propulsionType: 'Twin 2D Vectoring Turbopump Plasma Core',
    operationalCeiling: 'All-Atmosphere Covert Ingress',
    manufactureOrigin: 'Shadowline Orbital (Titan)',
    primaryColor: '#090d16',
    accentColor: '#a855f7',
    visorColor: '#7e22ce',
    footpadSpan: 72.5,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -55.1 },
      leftShoulder: { x: -47.85, y: 14.5 },
      rightShoulder: { x: 47.85, y: 14.5 },
      leftHip: { x: -31.9, y: 26.1 },
      rightHip: { x: 31.9, y: 26.1 },
      leftFoot: { x: -36.25, y: 42.8 },
      rightFoot: { x: 36.25, y: 42.8 },
      leftThrusterPos: { x: -19.58, y: 34.8 },
      rightThrusterPos: { x: 19.58, y: 34.8 },
    },
    stats: {
      agility: 3,
      fuelTank: 4,
      stability: 4,
      thrust: 4,
      armor: 4,
    },
  },
  {
    id: 'apollo',
    name: 'Apollo Recon',
    codename: 'LM-Scout Mk IV',
    tagline: 'Standard Balanced Recon Lander',
    classType: 'Small Recon',
    description: 'A finely tuned, all-purpose exploration lander with balanced handling, reliable fuel reserves, gold thermal quilting, and responsive reaction thrusters.',
    width: 90,
    height: 88,
    renderScale: 1.45,
    maxFuel: 160,
    thrustMultiplier: 1.0,
    torqueMultiplier: 1.0,
    mass: 1.0,
    armor: 0.25,
    emptyMassTons: 7.2,
    maxThrustKn: 95,
    twr: 1.34,
    rcsResponseMs: 30,
    armorRatingMm: 45,
    cargoHookCapacityKg: 500,
    roverBayCapacity: 'Light Scientific Gear Only',
    propulsionType: 'Aerozine-50 / NTO Bipropellant',
    operationalCeiling: 'All Planetary Regimes',
    manufactureOrigin: 'Lunar Surface Systems (Luna)',
    primaryColor: '#f8fafc',
    accentColor: '#38bdf8',
    visorColor: '#0284c7',
    footpadSpan: 81.2,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -39.15 },
      leftShoulder: { x: -30.45, y: -7.25 },
      rightShoulder: { x: 30.45, y: -7.25 },
      leftHip: { x: -27.55, y: 31.9 },
      rightHip: { x: 27.55, y: 31.9 },
      leftFoot: { x: -40.6, y: 43.5 },
      rightFoot: { x: 40.6, y: 43.5 },
      leftThrusterPos: { x: -19.58, y: 35.53 },
      rightThrusterPos: { x: 19.58, y: 35.53 },
    },
    stats: {
      agility: 4,
      fuelTank: 3,
      stability: 4,
      thrust: 3,
      armor: 3,
    },
  },

  // =========================================================================
  // 2. MEDIUM EXPLORER & TACTICAL CRAFTS (Extended Range, Multi-Thruster, Heavy Gear)
  // =========================================================================
  {
    id: 'aegis',
    name: 'Clairvoyant Dropship',
    codename: '12-X Nomadic Dropship',
    tagline: 'Heavy Tactical VTOL Gunship & Surface Dropship',
    classType: 'Heavy Dropship',
    description: 'The iconic 12-X Nomadic heavy tactical dropship "Clairvoyant" from Quantum: Origins. Re-engineered to true heavy dropship scale (+30% volume) with a low-slung, high-stability ground clearance profile, ballistic ceramic cab armor, heavy cylindrical reactor spine, canted vertical tail fin with crosshair roundel, dual high-output ventral VTOL lift thrusters mounted below the belly, and heavy-duty squat hydraulic outrigger landing gear.',
    width: 146,
    height: 112,
    renderScale: 1.90,
    maxFuel: 240,
    thrustMultiplier: 1.28,
    torqueMultiplier: 1.15,
    mass: 1.5,
    armor: 0.52,
    emptyMassTons: 21.5,
    maxThrustKn: 320,
    twr: 1.48,
    rcsResponseMs: 38,
    armorRatingMm: 135,
    cargoHookCapacityKg: 2400,
    roverBayCapacity: 'Clairvoyant Dropship Internal Vehicle & Troop Hold',
    propulsionType: 'Dual Ventral VTOL Lift Thrusters + Aft Vectoring Nozzles',
    operationalCeiling: 'Tactical Planetary Ingress & Heavy Surface Logistics',
    manufactureOrigin: 'Nomadic Heavy Industries (Quantum: Origins)',
    primaryColor: '#c2bcb0',
    accentColor: '#eab308',
    visorColor: '#0284c7',
    footpadSpan: 87.4,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: -74.5, y: 4.75 },
      leftShoulder: { x: -41.8, y: -26.6 },
      rightShoulder: { x: 55.1, y: -58.9 },
      leftHip: { x: -49.4, y: 22.8 },
      rightHip: { x: 45.6, y: 22.8 },
      leftFoot: { x: -45.6, y: 38.0 },
      rightFoot: { x: 41.8, y: 38.0 },
      leftThrusterPos: { x: -26.6, y: 35.15 },
      rightThrusterPos: { x: 30.4, y: 35.15 },
    },
    stats: {
      agility: 3,
      fuelTank: 5,
      stability: 5,
      thrust: 4,
      armor: 5,
    },
  },
  {
    id: 'nebula',
    name: 'Nebula Starchaser',
    codename: 'NX-Cosmos Delta',
    tagline: 'Atmospheric Delta Cruiser',
    classType: 'Medium Explorer',
    description: 'Features swept aerodynamic carbon-nanotube wings and dual vectoring plasma exhausts. Glides smoothly through atmospheric drafts and high crosswinds.',
    width: 87,
    height: 86,
    renderScale: 1.5,
    maxFuel: 180,
    thrustMultiplier: 1.15,
    torqueMultiplier: 1.2,
    mass: 0.95,
    armor: 0.20,
    emptyMassTons: 8.4,
    maxThrustKn: 120,
    twr: 1.45,
    rcsResponseMs: 25,
    armorRatingMm: 45,
    cargoHookCapacityKg: 550,
    roverBayCapacity: 'None (Aero Wing Structure)',
    propulsionType: 'Dual Aerospike Rocket Exhausts',
    operationalCeiling: 'Dense Gas & Vapor Atmospheres',
    manufactureOrigin: 'Cosmos Astroworks (Titan)',
    primaryColor: '#f1f5f9',
    accentColor: '#8b5cf6',
    visorColor: '#7c3aed',
    footpadSpan: 72.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -37.5 },
      leftShoulder: { x: -43.5, y: -21.0 },
      rightShoulder: { x: 43.5, y: -21.0 },
      leftHip: { x: -40.5, y: 34.5 },
      rightHip: { x: 40.5, y: 34.5 },
      leftFoot: { x: -36.0, y: 45.0 },
      rightFoot: { x: 36.0, y: 45.0 },
      leftThrusterPos: { x: -31.5, y: 33.0 },
      rightThrusterPos: { x: 31.5, y: 33.0 },
    },
    stats: {
      agility: 4,
      fuelTank: 4,
      stability: 4,
      thrust: 4,
      armor: 3,
    },
  },
  {
    id: 'vanguard',
    name: 'Vanguard Exoship',
    codename: 'VG-Exo Crusader',
    tagline: 'Multi-Stage Deep Core Explorer',
    classType: 'Medium Explorer',
    description: 'A towering, multi-module deep space cruiser wrapped in gold thermal foil with quad landing stabilizers and high-efficiency auxiliary booster tanks.',
    width: 87,
    height: 102,
    renderScale: 1.55,
    maxFuel: 220,
    thrustMultiplier: 1.25,
    torqueMultiplier: 1.05,
    mass: 1.2,
    armor: 0.35,
    emptyMassTons: 11.2,
    maxThrustKn: 165,
    twr: 1.50,
    rcsResponseMs: 32,
    armorRatingMm: 70,
    cargoHookCapacityKg: 750,
    roverBayCapacity: 'Modular Equipment Container',
    propulsionType: 'Nuclear Thermal Closed-Cycle Gas Core',
    operationalCeiling: 'Interplanetary Outer Reaches',
    manufactureOrigin: 'Vanguard Orbital Yards (Mars)',
    primaryColor: '#f8fafc',
    accentColor: '#eab308',
    visorColor: '#ca8a04',
    footpadSpan: 86.8,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -55.8 },
      leftShoulder: { x: -27.9, y: 3.1 },
      rightShoulder: { x: 27.9, y: 3.1 },
      leftHip: { x: -27.9, y: 29.45 },
      rightHip: { x: 27.9, y: 29.45 },
      leftFoot: { x: -43.4, y: 43.4 },
      rightFoot: { x: 43.4, y: 43.4 },
      leftThrusterPos: { x: -19.38, y: 34.1 },
      rightThrusterPos: { x: 19.38, y: 34.1 },
    },
    stats: {
      agility: 3,
      fuelTank: 5,
      stability: 4,
      thrust: 5,
      armor: 4,
    },
  },
  {
    id: 'orion',
    name: 'Orion Surveyor',
    codename: 'OR-300 Deep Space Scout',
    tagline: 'Twin-Boom Long-Range Science Vessel',
    classType: 'Medium Explorer',
    description: 'Equipped with twin sensor booms, high-output fuel reserves, and multi-spectral spectrometers. Delivers exceptional stability in complex magnetic cavern anomalies.',
    width: 92,
    height: 90,
    renderScale: 1.52,
    maxFuel: 210,
    thrustMultiplier: 1.18,
    torqueMultiplier: 1.10,
    mass: 1.10,
    armor: 0.32,
    emptyMassTons: 10.5,
    maxThrustKn: 145,
    twr: 1.41,
    rcsResponseMs: 28,
    armorRatingMm: 65,
    cargoHookCapacityKg: 700,
    roverBayCapacity: 'Sample Recovery Locker Deck',
    propulsionType: 'Magnetoplasmadynamic Vector Core',
    operationalCeiling: 'Deep Planetary Interior Chasms',
    manufactureOrigin: 'Orion Stellar Consortium (Vesta)',
    primaryColor: '#0f172a',
    accentColor: '#38bdf8',
    visorColor: '#0369a1',
    footpadSpan: 88.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -45.0 },
      leftShoulder: { x: -44.0, y: -10.0 },
      rightShoulder: { x: 44.0, y: -10.0 },
      leftHip: { x: -32.0, y: 28.0 },
      rightHip: { x: 32.0, y: 28.0 },
      leftFoot: { x: -42.56, y: 45.6 },
      rightFoot: { x: 42.56, y: 45.6 },
      leftThrusterPos: { x: -24.0, y: 34.0 },
      rightThrusterPos: { x: 24.0, y: 34.0 },
    },
    stats: {
      agility: 4,
      fuelTank: 4,
      stability: 4,
      thrust: 4,
      armor: 4,
    },
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie Tactical',
    codename: 'VK-55 Armored Dropship',
    tagline: 'Reinforced Combat Dropship',
    classType: 'Medium Explorer',
    description: 'Armored titanium hull plating with quad gimbal nozzles. Built to withstand high-velocity rock collisions and turbulent geothermal venting.',
    width: 96,
    height: 92,
    renderScale: 1.54,
    maxFuel: 200,
    thrustMultiplier: 1.28,
    torqueMultiplier: 1.05,
    mass: 1.25,
    armor: 0.52,
    emptyMassTons: 12.0,
    maxThrustKn: 175,
    twr: 1.48,
    rcsResponseMs: 34,
    armorRatingMm: 110,
    cargoHookCapacityKg: 800,
    roverBayCapacity: 'Reinforced Tactical Pod Deck',
    propulsionType: 'Quad Quad-Chamber Methalox Thrust Array',
    operationalCeiling: 'Hostile Thermal & Debris Zones',
    manufactureOrigin: 'Valhalla Defense Yards (Vespera)',
    primaryColor: '#1e293b',
    accentColor: '#ef4444',
    visorColor: '#b91c1c',
    footpadSpan: 89.3,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 0, y: -45.0 },
      leftShoulder: { x: -41.6, y: 3.0 },
      rightShoulder: { x: 41.6, y: 3.0 },
      leftHip: { x: -32.3, y: 26.2 },
      rightHip: { x: 32.3, y: 26.2 },
      leftFoot: { x: -44.66, y: 47.74 },
      rightFoot: { x: 44.66, y: 47.74 },
      leftThrusterPos: { x: -18.5, y: 33.9 },
      rightThrusterPos: { x: 18.5, y: 33.9 },
    },
    stats: {
      agility: 3,
      fuelTank: 4,
      stability: 4,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'nautilus',
    name: 'Nautilus Vector',
    codename: 'NX-5 Modular Scout',
    tagline: 'High-Mobility Tactical Exploration Lander',
    classType: 'Medium Explorer',
    description: 'An agile, asymmetric modular expedition craft featuring a distinctive spiral bow canopy with amber visor ring, an angled dorsal rocket pod, triple belly reaction thrusters, and stamped cross-pad landing skids.',
    width: 96,
    height: 90,
    renderScale: 1.52,
    maxFuel: 210,
    thrustMultiplier: 1.20,
    torqueMultiplier: 1.30,
    mass: 1.05,
    armor: 0.38,
    emptyMassTons: 9.2,
    maxThrustKn: 145,
    twr: 1.65,
    rcsResponseMs: 24,
    armorRatingMm: 75,
    cargoHookCapacityKg: 650,
    roverBayCapacity: 'Light Scientific Rig (Non-Heavy)',
    propulsionType: 'Vectored Ion-Plasma Aerospike Array',
    operationalCeiling: 'Low-G Moons, Canyons & Slalom Insertion',
    manufactureOrigin: 'Orbital Dynamics Consortium (Ganymede)',
    primaryColor: '#f8fafc',
    accentColor: '#eab308',
    visorColor: '#facc15',
    footpadSpan: 76.0,
    canCarryVehicles: false,
    isHeavyVehicleCarrier: false,
    localPoints: {
      nose: { x: 50.0, y: -8.0 },
      leftShoulder: { x: -38.0, y: -38.0 },
      rightShoulder: { x: 38.0, y: -35.0 },
      leftHip: { x: -44.0, y: 22.0 },
      rightHip: { x: 44.0, y: 22.0 },
      leftFoot: { x: -32.0, y: 44.0 },
      rightFoot: { x: 38.0, y: 44.0 },
      leftThrusterPos: { x: -38.0, y: 28.0 },
      rightThrusterPos: { x: 14.0, y: 28.0 },
    },
    stats: {
      agility: 4,
      fuelTank: 4,
      stability: 4,
      thrust: 4,
      armor: 3,
    },
  },

  // =========================================================================
  // 3. HEAVY INDUSTRIAL TRANSPORTS & ROVER CARRIERS (Vehicles, Ramps, Heavy Bays)
  // =========================================================================
  {
    id: 'titan',
    name: 'Titan Behemoth',
    codename: 'HC-9000 Dreadnought',
    tagline: 'Heavy Industrial Cargo Hauler',
    classType: 'Heavy Transport',
    description: 'An ultra-wide, heavily armored freight vessel equipped with massive high-capacity fuel tanks, high-torque twin gimbals, and vehicle transport capability.',
    width: 126,
    height: 100,
    renderScale: 1.85,
    maxFuel: 260,
    thrustMultiplier: 1.35,
    torqueMultiplier: 0.85,
    mass: 1.35,
    armor: 0.50,
    emptyMassTons: 16.5,
    maxThrustKn: 240,
    twr: 1.48,
    rcsResponseMs: 45,
    armorRatingMm: 120,
    cargoHookCapacityKg: 1200,
    roverBayCapacity: 'Full Heavy Rover Transport Deck',
    propulsionType: 'Dual Heavy Gimballed Hydrolox Engines',
    operationalCeiling: 'High-Gravity Freight Transport',
    manufactureOrigin: 'Titan Industrial Shipworks (Titan)',
    primaryColor: '#e2e8f0',
    accentColor: '#f59e0b',
    visorColor: '#ea580c',
    footpadSpan: 120.3,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 0, y: -40.7 },
      leftShoulder: { x: -62.9, y: 3.7 },
      rightShoulder: { x: 62.9, y: 3.7 },
      leftHip: { x: -51.8, y: 33.3 },
      rightHip: { x: 51.8, y: 33.3 },
      leftFoot: { x: -64.75, y: 51.8 },
      rightFoot: { x: 64.75, y: 51.8 },
      leftThrusterPos: { x: -35.15, y: 41.63 },
      rightThrusterPos: { x: 35.15, y: 41.63 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'goliath',
    name: 'Goliath Carrier',
    codename: 'CT-950 Colossus Hauler',
    tagline: 'Ultra-Wide Heavy Vehicle & Rover Carrier',
    classType: 'Rover Transporter',
    description: 'A massive, wide-bodied planetary transporter equipped with hydraulic landing ramps, wide-span outriggers, and a pressurized interior hold for transporting heavy rovers and industrial trucks.',
    width: 127,
    height: 130,
    renderScale: 1.68,
    maxFuel: 340,
    thrustMultiplier: 1.45,
    torqueMultiplier: 0.78,
    mass: 1.65,
    armor: 0.60,
    emptyMassTons: 22.0,
    maxThrustKn: 320,
    twr: 1.48,
    rcsResponseMs: 50,
    armorRatingMm: 150,
    cargoHookCapacityKg: 2000,
    roverBayCapacity: 'Pressurized Dual Rover Ramp Bay',
    propulsionType: 'Quad Staged Plasma Thrusters + Lift Jets',
    operationalCeiling: 'Planetary Surface Base Logistics',
    manufactureOrigin: 'Colossus Heavy Transports (Luna)',
    primaryColor: '#f8fafc',
    accentColor: '#f59e0b',
    visorColor: '#0ea5e9',
    footpadSpan: 127.68,
    isHeavyVehicleCarrier: true,
    canCarryVehicles: true,
    localPoints: {
      nose: { x: -47.04, y: -70.56 },
      leftShoulder: { x: -60.48, y: -57.12 },
      rightShoulder: { x: 60.48, y: 8.4 },
      leftHip: { x: -60.48, y: 26.88 },
      rightHip: { x: 60.48, y: 26.88 },
      leftFoot: { x: -63.84, y: 53.76 },
      rightFoot: { x: 63.84, y: 53.76 },
      extraLeftFoot: { x: -26.88, y: 53.76 },
      extraRightFoot: { x: 26.88, y: 53.76 },
      leftThrusterPos: { x: -45.36, y: 32.76 },
      rightThrusterPos: { x: 43.68, y: 32.76 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'behemoth',
    name: 'Behemoth-IX',
    codename: 'BH-900 Dreadnought',
    tagline: 'Massive Asymmetric Industrial Hauler',
    classType: 'Rover Transporter',
    description: 'A monstrous industrial transport featuring an offset starboard command bridge, a portside heavy cargo gantry truss, and a forward hydraulic ramp for loading heavy planetary vehicles.',
    width: 127,
    height: 133,
    renderScale: 1.68,
    maxFuel: 360,
    thrustMultiplier: 1.5,
    torqueMultiplier: 0.72,
    mass: 1.75,
    armor: 0.65,
    emptyMassTons: 25.4,
    maxThrustKn: 360,
    twr: 1.45,
    rcsResponseMs: 55,
    armorRatingMm: 175,
    cargoHookCapacityKg: 2500,
    roverBayCapacity: 'Asymmetric Heavy Vehicle Crane Ramp',
    propulsionType: 'Offset Dual-Chamber Fusion Torch Nozzles',
    operationalCeiling: 'Deep Mine Shaft Haulage',
    manufactureOrigin: 'Ironclad Heavy Foundries (Ares)',
    primaryColor: '#e2e8f0',
    accentColor: '#f97316',
    visorColor: '#0284c7',
    footpadSpan: 127.68,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 47.04, y: -72.24 },
      leftShoulder: { x: -60.48, y: -40.32 },
      rightShoulder: { x: 60.48, y: -57.12 },
      leftHip: { x: -60.48, y: 26.88 },
      rightHip: { x: 60.48, y: 26.88 },
      leftFoot: { x: -63.84, y: 55.44 },
      rightFoot: { x: 63.84, y: 55.44 },
      extraLeftFoot: { x: -25.2, y: 55.44 },
      extraRightFoot: { x: 25.2, y: 55.44 },
      leftThrusterPos: { x: -40.32, y: 32.76 },
      rightThrusterPos: { x: 43.68, y: 32.76 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'leviathan',
    name: 'Leviathan Titan',
    codename: 'LV-880 Split-Hull Carrier',
    tagline: 'Asymmetric Twin-Hull Supercarrier',
    classType: 'Rover Transporter',
    description: 'An immense asymmetric catamaran supercarrier with a heavy armored vehicle hangar on the port sponson, an offset starboard sensor spine, and an articulated hydraulic ramp door.',
    width: 140,
    height: 141,
    renderScale: 1.75,
    maxFuel: 380,
    thrustMultiplier: 1.55,
    torqueMultiplier: 0.70,
    mass: 1.85,
    armor: 0.70,
    emptyMassTons: 28.5,
    maxThrustKn: 410,
    twr: 1.47,
    rcsResponseMs: 58,
    armorRatingMm: 190,
    cargoHookCapacityKg: 3000,
    roverBayCapacity: 'Catamaran Dual-Sponson Heavy Hangar',
    propulsionType: 'Triple High-Volume Deuterium Jets',
    operationalCeiling: 'Planetary Citadel Logistics',
    manufactureOrigin: 'Leviathan Oceanic Orbital (Europa)',
    primaryColor: '#0f172a',
    accentColor: '#06b6d4',
    visorColor: '#38bdf8',
    footpadSpan: 140.0,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 38.5, y: -77.0 },
      leftShoulder: { x: -66.5, y: -49.0 },
      rightShoulder: { x: 66.5, y: -28.0 },
      leftHip: { x: -66.5, y: 28.0 },
      rightHip: { x: 66.5, y: 28.0 },
      leftFoot: { x: -70.0, y: 59.5 },
      rightFoot: { x: 70.0, y: 59.5 },
      extraLeftFoot: { x: -26.25, y: 59.5 },
      extraRightFoot: { x: 26.25, y: 59.5 },
      leftThrusterPos: { x: -42.0, y: 34.13 },
      rightThrusterPos: { x: 49.0, y: 34.13 },
    },
    stats: {
      agility: 1,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'mammoth',
    name: 'Mammoth Rig',
    codename: 'MR-700 Excavator Carrier',
    tagline: 'Heavy Logistics Mobile Base Carrier',
    classType: 'Rover Transporter',
    description: 'A formidable deep-mining transport equipped with a portside hydraulic crane boom, offset starboard fuel refinery columns, and an ultra-wide planetary crawler ramp bay.',
    width: 127,
    height: 119,
    renderScale: 1.68,
    maxFuel: 360,
    thrustMultiplier: 1.48,
    torqueMultiplier: 0.74,
    mass: 1.80,
    armor: 0.68,
    emptyMassTons: 26.8,
    maxThrustKn: 390,
    twr: 1.46,
    rcsResponseMs: 56,
    armorRatingMm: 180,
    cargoHookCapacityKg: 2800,
    roverBayCapacity: 'Heavy Mobile Base Ramp & Crane Bay',
    propulsionType: 'Refinery Fed Thermal Rocket Array',
    operationalCeiling: 'Deep Volcanic & Mining Rifts',
    manufactureOrigin: 'Mammoth Core Engineering (Tartarus)',
    primaryColor: '#334155',
    accentColor: '#eab308',
    visorColor: '#e11d48',
    footpadSpan: 127.68,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 57.12, y: -57.12 },
      leftShoulder: { x: -63.84, y: -47.04 },
      rightShoulder: { x: 63.84, y: -57.12 },
      leftHip: { x: -63.84, y: 26.88 },
      rightHip: { x: 63.84, y: 26.88 },
      leftFoot: { x: -63.84, y: 57.12 },
      rightFoot: { x: 63.84, y: 57.12 },
      extraLeftFoot: { x: -25.2, y: 57.12 },
      extraRightFoot: { x: 25.2, y: 57.12 },
      leftThrusterPos: { x: -40.32, y: 32.76 },
      rightThrusterPos: { x: 45.36, y: 32.76 },
    },
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'juggernaut',
    name: 'Juggernaut Lifter',
    codename: 'JG-1200 Planetary Heavy Lifter',
    tagline: 'Quad-Engine Super-Heavy Rover Carrier',
    classType: 'Rover Transporter',
    description: 'The pinnacle of heavy surface logistics: equipped with quad gimballed rocket thrusters, reinforced tungsten landing outriggers, and dual drive-through hydraulic vehicle ramps.',
    width: 144,
    height: 140,
    renderScale: 1.76,
    maxFuel: 420,
    thrustMultiplier: 1.62,
    torqueMultiplier: 0.68,
    mass: 2.05,
    armor: 0.75,
    emptyMassTons: 32.0,
    maxThrustKn: 480,
    twr: 1.52,
    rcsResponseMs: 62,
    armorRatingMm: 220,
    cargoHookCapacityKg: 3500,
    roverBayCapacity: 'Dual Drive-Through Heavy Rover Ramp Hold',
    propulsionType: 'Quad Heavy Fusion Torch Combustion Array',
    operationalCeiling: 'Supermassive Gravity Worlds & Citadels',
    manufactureOrigin: 'Juggernaut Fleet Yards (Omega Prime)',
    primaryColor: '#0f172a',
    accentColor: '#10b981',
    visorColor: '#059669',
    footpadSpan: 142.0,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 0, y: -74.0 },
      leftShoulder: { x: -68.0, y: -45.0 },
      rightShoulder: { x: 68.0, y: -45.0 },
      leftHip: { x: -68.0, y: 28.0 },
      rightHip: { x: 68.0, y: 28.0 },
      leftFoot: { x: -79.2, y: 66.88 },
      rightFoot: { x: 79.2, y: 66.88 },
      extraLeftFoot: { x: -31.68, y: 66.88 },
      extraRightFoot: { x: 31.68, y: 66.88 },
      leftThrusterPos: { x: -46.0, y: 35.0 },
      rightThrusterPos: { x: 46.0, y: 35.0 },
    },
    stats: {
      agility: 1,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'nutcracker',
    name: 'Nutcracker',
    codename: 'EX-920 Heavy Excavator',
    tagline: 'Deep-Crust Industrial Crawler Carrier',
    classType: 'Rover Transporter',
    description: 'A heavy desert-planet crawler carrier equipped with an aft rock-crusher drill bore, panoramic bridge superstructure, twin pneumatic conduit banks, and an articulated hydraulic belly ramp hold for planetary rovers.',
    width: 136,
    height: 124,
    renderScale: 1.70,
    maxFuel: 375,
    thrustMultiplier: 1.50,
    torqueMultiplier: 0.72,
    mass: 1.82,
    armor: 0.72,
    emptyMassTons: 27.5,
    maxThrustKn: 405,
    twr: 1.48,
    rcsResponseMs: 58,
    armorRatingMm: 210,
    cargoHookCapacityKg: 3200,
    roverBayCapacity: 'Underslung Hydraulic Crawler Ramp Hold',
    propulsionType: 'Asymmetric Quad Deuterium Combustion Array',
    operationalCeiling: 'Extreme Gravity Desert & Mining Outposts',
    manufactureOrigin: 'Caelum Heavy Industries (Arakkis Outpost)',
    primaryColor: '#b84538',
    accentColor: '#d4b276',
    visorColor: '#38bdf8',
    footpadSpan: 136.0,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 44.0, y: -64.0 },
      leftShoulder: { x: -64.0, y: -45.0 },
      rightShoulder: { x: 64.0, y: -45.0 },
      leftHip: { x: -64.0, y: 28.0 },
      rightHip: { x: 64.0, y: 28.0 },
      leftFoot: { x: -68.0, y: 57.8 },
      rightFoot: { x: 68.0, y: 57.8 },
      extraLeftFoot: { x: -28.0, y: 57.8 },
      extraRightFoot: { x: 28.0, y: 57.8 },
      leftThrusterPos: { x: -38.0, y: 34.0 },
      rightThrusterPos: { x: 40.0, y: 34.0 },
    },
    // Collision hull derived from drawNutcracker() geometry. Physics applies
    // transformPoint() (rotation + translation) with NO renderScale, while the
    // renderer draws hull coords under ctx.scale(renderScale) — so these points
    // are in renderScale-scaled units (raw draw coords x 1.70), matching
    // localPoints (e.g. leftFoot.y 57.8 = footPadY 34 x 1.70).
    // Vertices (clockwise from aft bottom-left) enclose the full silhouette:
    // aft drill arm (rotated -0.24 rad about (-40,-21)), hull blocks, bridge,
    // antenna beacon, searchlight projector, and both thruster bell lips.
    collisionPolygon: [
      { x: -71.4, y: 27.2 }, // aft hull bottom-left
      { x: -74.8, y: -27.2 }, // drill bracket bottom-left
      { x: -87.7, y: -51.9 }, // drill barrel far top-left
      { x: -58.0, y: -59.2 }, // drill barrel top (highest aft point)
      { x: -59.5, y: -34.0 }, // aft hull chamfer corner
      { x: 40.8, y: -34.0 }, // hull top run (aft + fwd blocks)
      { x: 51.0, y: -51.0 }, // bridge roof left transition
      { x: 59.5, y: -74.0 }, // antenna beacon top
      { x: 74.8, y: -61.2 }, // searchlight projector top-front
      { x: 74.8, y: 27.2 }, // hull floor front corner
      { x: 64.6, y: 40.8 }, // forward thruster lip outer
      { x: 37.4, y: 40.8 }, // forward thruster lip inner
      { x: 37.4, y: 27.2 }, // forward thruster inner top (belly start)
      { x: -40.8, y: 27.2 }, // belly end (aft thruster top-right)
      { x: -40.8, y: 40.8 }, // aft thruster lip inner
      { x: -64.6, y: 40.8 }, // aft thruster lip outer
    ],
    stats: {
      agility: 2,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
  {
    id: 'eagle',
    name: 'Eagle Transporter',
    codename: 'Alpha Eagle-One Mk IV',
    tagline: 'Modular Deep-Space Transport & Heavy Cargo Lander',
    classType: 'Heavy Transport',
    description: 'The iconic modular transport lander inspired by Space: 1999. Engineered with an open tubular spaceframe catwalk, interchangeable central cargo/passenger hold, forward beak cockpit module, 4-way RCS outrigger pods, dual downward VTOL lift bells, and quad aft nuclear fusion engines.',
    width: 138,
    height: 84,
    renderScale: 1.58,
    maxFuel: 330,
    thrustMultiplier: 1.40,
    torqueMultiplier: 0.90,
    mass: 1.48,
    armor: 0.54,
    emptyMassTons: 19.2,
    maxThrustKn: 295,
    twr: 1.52,
    rcsResponseMs: 36,
    armorRatingMm: 135,
    cargoHookCapacityKg: 2500,
    roverBayCapacity: 'Moonbase Alpha Modular Cargo & Rover Hold',
    propulsionType: 'Quad S-IV Nuclear Fusion Rockets + Dual Belly VTOL Lift Bells',
    operationalCeiling: 'Lunar Recon, Deep-Space Cargo & Planetary Surface Logistics',
    manufactureOrigin: 'Moonbase Alpha Technical Section (Luna Recon Sector 1)',
    primaryColor: '#f8fafc',
    accentColor: '#ef4444',
    visorColor: '#0f172a',
    footpadSpan: 110.6,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: 68.0, y: 0.0 },
      leftShoulder: { x: -44.0, y: -25.0 },
      rightShoulder: { x: 44.0, y: -25.0 },
      leftHip: { x: -42.0, y: 15.0 },
      rightHip: { x: 42.0, y: 15.0 },
      leftFoot: { x: -55.3, y: 34.8 },
      rightFoot: { x: 55.3, y: 34.8 },
      leftThrusterPos: { x: -17.4, y: 23.7 },
      rightThrusterPos: { x: 17.4, y: 23.7 },
    },
    // Collision hull derived from drawEagle() geometry (raw draw coords x 1.58,
    // physics applies rotation+translation with NO renderScale). Traced clockwise
    // around the full silhouette: quad fusion engine block, tanks, dorsal truss,
    // cargo pod, VTOL bells, outrigger RCS pods, landing gear, and beak cockpit.
    collisionPolygon: [
      { x: -112.2, y: 23.7 }, // aft engine block bottom-rear
      { x: -112.2, y: -22.9 }, // aft engine block top-rear
      { x: -80.6, y: -19.6 }, // propellant tank top
      { x: -71.1, y: -24.5 }, // aft truss collar
      { x: -37.9, y: -29.2 }, // raised bridge truss top (aft)
      { x: 34.0, y: -29.2 }, // raised bridge truss top (fwd)
      { x: 66.4, y: -24.5 }, // fwd truss collar top
      { x: 70.3, y: -24.5 }, // collar outer-top
      { x: 70.3, y: -11.1 }, // collar outer-bottom
      { x: 71.9, y: -14.2 }, // beak top start
      { x: 85.3, y: -14.2 }, // beak top
      { x: 94.8, y: -14.2 }, // beak top curve
      { x: 101.1, y: -9.2 }, // beak upper control
      { x: 107.9, y: -0.9 }, // nose probe tip (top)
      { x: 107.9, y: 1.0 }, // nose probe tip (bottom)
      { x: 105.1, y: 1.6 }, // beak underside root
      { x: 101.1, y: 8.5 }, // beak lower control
      { x: 94.8, y: 12.5 }, // beak bottom
      { x: 85.3, y: 12.5 }, // beak bottom mid
      { x: 71.9, y: 12.5 }, // beak bottom start
      { x: 67.9, y: 13.4 }, // service collar bottom
      { x: 64.0, y: 38.9 }, // fwd footpad outer-bottom
      { x: 43.5, y: 38.9 }, // fwd footpad inner-bottom
      { x: 37.9, y: 12.5 }, // pod fwd chamfer
      { x: 34.8, y: 15.0 }, // pod bottom fwd
      { x: 25.1, y: 16.6 }, // fwd VTOL bell outer-top
      { x: 25.1, y: 26.2 }, // fwd VTOL bell outer-bottom
      { x: 8.9, y: 25.9 }, // fwd VTOL bell inner-bottom
      { x: 13.8, y: 16.9 }, // fwd VTOL pylon inner
      { x: -13.8, y: 16.9 }, // aft VTOL pylon inner
      { x: -8.9, y: 25.9 }, // aft VTOL bell inner-bottom
      { x: -25.1, y: 26.2 }, // aft VTOL bell outer-bottom
      { x: -25.1, y: 16.6 }, // aft VTOL bell outer-top
      { x: -34.8, y: 15.0 }, // pod bottom aft
      { x: -37.9, y: 12.5 }, // pod aft chamfer
      { x: -43.5, y: 38.9 }, // aft footpad inner-bottom
      { x: -64.0, y: 38.9 }, // aft footpad outer-bottom
    ],
    stats: {
      agility: 3,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 4,
    },
  },
  {
    id: 'vulcan',
    name: 'Aegis Vulcan',
    codename: 'AV-17 Support Transport',
    tagline: 'Massive Military Support, Heavy Cargo & Multi-Role Fleet Transport',
    classType: 'Heavy Transport',
    description: 'The legendary Aegis Vulcan fleet support and heavy transport craft from Aegis Dynamics. Designed in an elongated heavy industrial side-profile with ballistic white cab armor, olive-drab military plate with weathered "R-17" tactical stencils, center drone operator airlock with Aegis insignia, underslung heavy propellant tank, dual ventral VTOL lift nozzles, and colossal hydraulic landing gear struts with articulated footpads.',
    width: 226,
    height: 72,
    renderScale: 1.55,
    maxFuel: 360,
    thrustMultiplier: 1.52,
    torqueMultiplier: 0.70,
    mass: 2.00,
    armor: 0.65,
    emptyMassTons: 29.5,
    maxThrustKn: 430,
    twr: 1.49,
    rcsResponseMs: 60,
    armorRatingMm: 165,
    cargoHookCapacityKg: 3400,
    roverBayCapacity: 'Aegis Heavy Cargo Hold & Drone Maintenance Bay',
    propulsionType: 'Dual High-Output Ventral VTOL Lift Thrusters + Aft Vectoring Nozzles',
    operationalCeiling: 'Deep-Space Fleet Support, Combat Logistics & Planetary Drops',
    manufactureOrigin: 'Aegis Dynamics Fleet Works (Sol Aerospace Sector)',
    primaryColor: '#3c4a36',
    accentColor: '#dc2626',
    visorColor: '#0f172a',
    footpadSpan: 114.7,
    canCarryVehicles: true,
    isHeavyVehicleCarrier: true,
    localPoints: {
      nose: { x: -112.4, y: -1.6 },
      leftShoulder: { x: -71.3, y: -29.5 },
      rightShoulder: { x: 102.3, y: -15.5 },
      leftHip: { x: -102.3, y: 4.7 },
      rightHip: { x: 112.4, y: 4.7 },
      leftFoot: { x: -49.6, y: 31.0 },
      rightFoot: { x: 65.1, y: 31.0 },
      leftThrusterPos: { x: -37.2, y: 25.58 },
      rightThrusterPos: { x: 55.8, y: 25.58 },
    },
    collisionPolygon: [
      { x: -112.4, y: -1.6 },
      { x: -108.5, y: -23.3 },
      { x: -105.4, y: -29.5 },
      { x: -71.3, y: -29.5 },
      { x: -12.4, y: -29.5 },
      { x: 21.7, y: -39.5 },
      { x: 48.8, y: -38.8 },
      { x: 65.1, y: -34.1 },
      { x: 86.8, y: -24.8 },
      { x: 102.3, y: -15.5 },
      { x: 108.5, y: -10.9 },
      { x: 112.4, y: -6.2 },
      { x: 112.4, y: 4.7 },
      { x: 108.5, y: 7.8 },
      { x: 102.3, y: 10.9 },
      { x: 102.3, y: 24.8 },
      { x: 83.7, y: 24.8 },
      { x: 70.5, y: 31.0 },
      { x: 59.7, y: 31.0 },
      { x: 55.8, y: 25.6 },
      { x: 7.8, y: 28.7 },
      { x: -37.2, y: 25.6 },
      { x: -44.2, y: 31.0 },
      { x: -55.0, y: 31.0 },
      { x: -71.3, y: 14.0 },
      { x: -102.3, y: 4.7 },
      { x: -110.8, y: 0.0 },
    ],
    stats: {
      agility: 1,
      fuelTank: 5,
      stability: 5,
      thrust: 5,
      armor: 5,
    },
  },
];

export function getShipConfig(modelId: ShipModelId = 'apollo'): ShipModelConfig {
  return SHIPS.find((s) => s.id === modelId) || SHIPS[0];
}

export const SHIP_MODELS = SHIPS;
